const aimProfileCopy = Object.freeze({
  en: Object.freeze({ eyebrow: 'YOUR AIM HISTORY', title: 'Personal aim profile', localNote: 'Saved only in this browser. Each completed test updates your profile.', currentRank: 'CURRENT FORM', tests: 'TESTS', best: 'PERSONAL BEST', average: 'ALL-TIME AVG', stability: 'AVG STABILITY', recent: 'LAST 7 RUNS', trendImproved: '{difference} {unit} faster than before', trendSlower: '{difference} {unit} slower than before', trendSteady: 'Holding steady', trendLabel: 'Reaction time trend across recent tests', clear: 'Clear local history', clearConfirm: 'Clear your reaction history from this browser?', fastLabel: 'FASTER', steadyLabel: 'TAKE YOUR TIME', yourMarker: 'YOU', nextGoal: 'NEXT TARGET', topRange: 'You reached the fastest bracket', improveGoal: '{difference} {unit} faster reaches {rank}', calibrationNote: 'One browser scale for mouse and touch. Device latency counts, so repeat runs show progress best.', rankFeedback_iron: 'Start with your own baseline. Device latency matters, so compare a few runs before judging.', rankFeedback_bronze: 'Baseline set. Try two more runs and focus on making each click feel consistent.', rankFeedback_silver: 'Your rhythm is settling in. Next, keep all three rounds close together.', rankFeedback_gold: 'A solid response. Consistency matters more than one lucky fast click.', rankFeedback_platinum: 'Speed and control are both online. Now chase your personal best.', rankFeedback_diamond: 'Quick response. Try to keep all three rounds near this pace.', rankFeedback_ascendant: 'Excellent browser reaction speed. Small gains now come from steadier input.', rankFeedback_immortal: 'Very fast. Repeat the test to prove you can hold this pace.', rankFeedback_radiant: 'Top bracket. Repeating it consistently is the real flex.' }),
  ja: Object.freeze({ eyebrow: 'エイム履歴', title: 'パーソナルエイムプロフィール', localNote: 'このブラウザ内だけに保存され、テスト完了ごとに更新されます。', currentRank: '現在の調子', tests: 'テスト回数', best: '自己ベスト', average: '通算平均', stability: '平均安定度', recent: '直近7回', trendImproved: '以前より{difference}{unit}高速', trendSlower: '以前より{difference}{unit}低速', trendSteady: '安定しています', trendLabel: '直近テストの反応速度推移', clear: 'この端末の履歴を消す', clearConfirm: 'このブラウザに保存された反応履歴を消しますか？', fastLabel: 'より速く', steadyLabel: '落ち着いて', yourMarker: 'あなた', nextGoal: '次の目標', topRange: '最速ゾーンに到達', improveGoal: 'あと{difference}{unit}で{rank}', calibrationNote: 'マウスとタッチ共通のブラウザ基準です。端末遅延も含まれるため、複数回の推移で見てください。', rankFeedback_iron: 'まずは自分の基準を作りましょう。端末の遅延もあるため、数回の推移で判断してください。', rankFeedback_bronze: '基準を記録できました。あと2回ほど試し、各ラウンドの差を小さくしましょう。', rankFeedback_silver: '反応のリズムが安定してきました。次は3ラウンドを近い記録にそろえましょう。', rankFeedback_gold: '十分に良い反応です。偶然の最速値より安定性を重視しましょう。', rankFeedback_platinum: '速さと安定性がそろっています。次は自己ベストを狙いましょう。', rankFeedback_diamond: 'かなり速い反応です。3ラウンドともこのペースを保てるか試しましょう。', rankFeedback_ascendant: '優れたブラウザ反応速度です。ここからは入力の安定が差になります。', rankFeedback_immortal: '非常に高速です。繰り返しても保てるか確認しましょう。', rankFeedback_radiant: '最上位ゾーンです。何度でも安定して出せれば本物です。' }),
  es: Object.freeze({ eyebrow: 'TU HISTORIAL', title: 'Perfil personal de puntería', localNote: 'Se guarda solo en este navegador y se actualiza al completar cada prueba.', currentRank: 'FORMA ACTUAL', tests: 'PRUEBAS', best: 'MEJOR MARCA', average: 'MEDIA TOTAL', stability: 'ESTABILIDAD MEDIA', recent: 'ÚLTIMAS 7', trendImproved: '{difference} {unit} más rápido que antes', trendSlower: '{difference} {unit} más lento que antes', trendSteady: 'Ritmo estable', trendLabel: 'Tendencia del tiempo de reacción en las últimas pruebas', clear: 'Borrar historial local', clearConfirm: '¿Borrar de este navegador todo tu historial de reacción?', fastLabel: 'MÁS RÁPIDO', steadyLabel: 'CON CALMA', yourMarker: 'TÚ', nextGoal: 'PRÓXIMO OBJETIVO', topRange: 'Llegaste al tramo más rápido', improveGoal: '{difference} {unit} menos para llegar a {rank}', calibrationNote: 'Una escala web para ratón y pantalla táctil. La latencia del dispositivo cuenta; compara varias pruebas.', rankFeedback_iron: 'Empieza por tu propia referencia. La latencia del dispositivo cuenta; compara varias pruebas.', rankFeedback_bronze: 'Ya tienes una base. Haz dos intentos más y reduce la diferencia entre clics.', rankFeedback_silver: 'Tu ritmo se está estabilizando. Ahora acerca los tres resultados.', rankFeedback_gold: 'Buena respuesta. La regularidad vale más que un solo clic afortunado.', rankFeedback_platinum: 'Velocidad y control están a buen nivel. Ahora persigue tu mejor marca.', rankFeedback_diamond: 'Respuesta rápida. Intenta mantener este ritmo en las tres rondas.', rankFeedback_ascendant: 'Excelente velocidad en navegador. Las mejoras pequeñas dependen de una entrada estable.', rankFeedback_immortal: 'Muy rápido. Repite la prueba para confirmar que puedes mantenerlo.', rankFeedback_radiant: 'Tramo superior. Repetirlo con regularidad es el verdadero logro.' }),
  'zh-CN': Object.freeze({ eyebrow: '你的瞄准记录', title: '个人瞄准档案', localNote: '只保存在当前浏览器；每次完成测试都会更新。', currentRank: '当前状态', tests: '测试次数', best: '个人最快', average: '历史平均', stability: '平均稳定度', recent: '最近 7 次', trendImproved: '比此前快 {difference} {unit}', trendSlower: '比此前慢 {difference} {unit}', trendSteady: '目前保持稳定', trendLabel: '最近几次反应速度变化', clear: '清除本机记录', clearConfirm: '要清除这个浏览器里的全部反应测试记录吗？', fastLabel: '更快', steadyLabel: '从容发挥', yourMarker: '你', nextGoal: '下一目标', topRange: '已进入最快区间', improveGoal: '再快 {difference} {unit} 可到 {rank}', calibrationNote: '同一标尺兼容鼠标和触控；设备延迟会计入结果，连续测试更能说明进步。', rankFeedback_iron: '先建立自己的基准；设备延迟也会影响结果，多测几次再看变化。', rankFeedback_bronze: '已经完成基线。再测两组，先把每轮波动降下来。', rankFeedback_silver: '反应节奏正在稳定，接下来关注连续三轮的波动。', rankFeedback_gold: '基础反应不错，稳定发挥比偶尔一次极快更重要。', rankFeedback_platinum: '速度和稳定性都在线，可以开始挑战自己的最佳成绩。', rankFeedback_diamond: '反应很快，继续保持三轮都接近这个水平。', rankFeedback_ascendant: '出色的浏览器反应速度，细微提升更依赖稳定输入。', rankFeedback_immortal: '非常快；先确认多次测试仍能保持同一水平。', rankFeedback_radiant: '顶级区间。重复测试仍然稳定，才是真正的强。' }),
  'pt-BR': Object.freeze({ eyebrow: 'SEU HISTÓRICO', title: 'Perfil pessoal de mira', localNote: 'Salvo apenas neste navegador e atualizado a cada teste concluído.', currentRank: 'FORMA ATUAL', tests: 'TESTES', best: 'RECORDE', average: 'MÉDIA GERAL', stability: 'ESTABILIDADE MÉDIA', recent: 'ÚLTIMOS 7', trendImproved: '{difference} {unit} mais rápido que antes', trendSlower: '{difference} {unit} mais lento que antes', trendSteady: 'Ritmo estável', trendLabel: 'Tendência do tempo de reação nos testes recentes', clear: 'Limpar histórico local', clearConfirm: 'Limpar deste navegador todo o seu histórico de reação?', fastLabel: 'MAIS RÁPIDO', steadyLabel: 'COM CALMA', yourMarker: 'VOCÊ', nextGoal: 'PRÓXIMA META', topRange: 'Você chegou à faixa mais rápida', improveGoal: '{difference} {unit} a menos para chegar a {rank}', calibrationNote: 'Uma escala web para mouse e toque. A latência do aparelho conta; compare várias tentativas.', rankFeedback_iron: 'Comece pela sua própria referência. A latência do aparelho conta; compare várias tentativas.', rankFeedback_bronze: 'A base está registrada. Faça mais duas tentativas e reduza a diferença entre os cliques.', rankFeedback_silver: 'Seu ritmo está estabilizando. Agora aproxime os três resultados.', rankFeedback_gold: 'Boa resposta. Consistência vale mais que um único clique de sorte.', rankFeedback_platinum: 'Velocidade e controle estão alinhados. Agora busque seu recorde.', rankFeedback_diamond: 'Resposta rápida. Tente manter esse ritmo nas três rodadas.', rankFeedback_ascendant: 'Excelente velocidade no navegador. Pequenos ganhos dependem de uma entrada estável.', rankFeedback_immortal: 'Muito rápido. Repita para confirmar que consegue manter o ritmo.', rankFeedback_radiant: 'Faixa máxima. Repetir com consistência é o verdadeiro destaque.' }),
})

const refinedCopy = Object.freeze({
  en: Object.freeze({
    currentRank: 'LATEST RUN', best: 'FASTEST ROUND', average: 'RECENT AVG', recentCount: 'LAST {count} RUNS', trendNotReady: 'Complete 3 more runs to unlock a trend', previousFaster: '{difference} {unit} faster than your previous run', previousSlower: '{difference} {unit} slower than your previous run', previousTied: 'Matched your previous run', calibrationNote: 'A browser reaction estimate, not your VALORANT rank. Compare runs made with the same device and input.', reliabilityHigh: 'Reliable run', reliabilityMedium: 'Usable estimate', reliabilityLow: 'Wide variation — retest recommended', profileReason_precision: 'Your fast, consistent clicks suit a minimal precision crosshair.', profileReason_balanced: 'Your pace is balanced, so a compact all-round crosshair is the safest fit.', profileReason_steady: 'A clear center helps stabilize runs with moderate variation.', profileReason_visibility: 'A more visible crosshair reduces search time when timing varies.', input_mouse: 'Mouse', input_touch: 'Touch', input_pen: 'Pen', input_keyboard: 'Keyboard', input_unknown: 'Device input', inputLabel: 'INPUT', historyScope: 'History compares completed runs in this browser.'
  }),
  ja: Object.freeze({
    currentRank: '直近の結果', best: '最速ラウンド', average: '直近の平均', recentCount: '直近{count}回', trendNotReady: 'あと3回で推移を表示できます', previousFaster: '前回より{difference}{unit}高速', previousSlower: '前回より{difference}{unit}低速', previousTied: '前回と同じ記録', calibrationNote: 'ブラウザ上の目安で、VALORANTのランクではありません。同じ端末・入力方法で比較してください。', reliabilityHigh: '安定した記録', reliabilityMedium: '参考にできる記録', reliabilityLow: 'ばらつきが大きいため再テスト推奨', profileReason_precision: '高速で安定した入力には、精密なミニマルクロスヘアが合います。', profileReason_balanced: 'バランスの良い反応には、扱いやすいコンパクト型が合います。', profileReason_steady: '中央が見やすい形は、入力のばらつきを抑えやすくします。', profileReason_visibility: '視認性の高い形なら、タイミングが揺れた時も見失いにくくなります。', input_mouse: 'マウス', input_touch: 'タッチ', input_pen: 'ペン', input_keyboard: 'キーボード', input_unknown: '入力端末', inputLabel: '入力方法', historyScope: 'このブラウザで完了したテストだけを比較します。'
  }),
  es: Object.freeze({
    currentRank: 'ÚLTIMA PRUEBA', best: 'RONDA MÁS RÁPIDA', average: 'MEDIA RECIENTE', recentCount: 'ÚLTIMAS {count}', trendNotReady: 'Completa 3 pruebas más para ver la tendencia', previousFaster: '{difference} {unit} más rápido que tu prueba anterior', previousSlower: '{difference} {unit} más lento que tu prueba anterior', previousTied: 'Igualaste tu prueba anterior', calibrationNote: 'Es una estimación del navegador, no tu rango de VALORANT. Compara pruebas con el mismo dispositivo y entrada.', reliabilityHigh: 'Prueba fiable', reliabilityMedium: 'Estimación útil', reliabilityLow: 'Mucha variación; conviene repetir', profileReason_precision: 'Tus clics rápidos y regulares encajan con una mira mínima de precisión.', profileReason_balanced: 'Tu ritmo equilibrado encaja con una mira compacta y versátil.', profileReason_steady: 'Un centro claro ayuda a estabilizar pruebas con variación moderada.', profileReason_visibility: 'Una mira más visible reduce el tiempo de búsqueda cuando cambia tu ritmo.', input_mouse: 'Ratón', input_touch: 'Táctil', input_pen: 'Lápiz', input_keyboard: 'Teclado', input_unknown: 'Entrada', inputLabel: 'ENTRADA', historyScope: 'El historial compara pruebas completadas en este navegador.'
  }),
  'zh-CN': Object.freeze({
    currentRank: '最近一次段位', best: '最快单轮', average: '近期平均', recentCount: '最近 {count} 次', trendNotReady: '再完成 3 次即可生成趋势', previousFaster: '比上一次快 {difference} {unit}', previousSlower: '比上一次慢 {difference} {unit}', previousTied: '与上一次成绩相同', calibrationNote: '这是浏览器反应估算，不代表游戏排位。请尽量用同一设备和输入方式比较。', reliabilityHigh: '本次发挥稳定', reliabilityMedium: '本次成绩可参考', reliabilityLow: '本次波动较大，建议重测', profileReason_precision: '你的点击又快又稳，适合更简洁的精确型准星。', profileReason_balanced: '你的速度与稳定性均衡，紧凑通用型最适合先上手。', profileReason_steady: '清楚的中心能帮助你减少中等幅度的点击波动。', profileReason_visibility: '更醒目的准星能在节奏波动时减少寻找中心的时间。', input_mouse: '鼠标', input_touch: '触控', input_pen: '触控笔', input_keyboard: '键盘', input_unknown: '当前设备', inputLabel: '输入方式', historyScope: '档案只比较当前浏览器中已完成的测试。'
  }),
  'pt-BR': Object.freeze({
    currentRank: 'ÚLTIMO TESTE', best: 'RODADA MAIS RÁPIDA', average: 'MÉDIA RECENTE', recentCount: 'ÚLTIMOS {count}', trendNotReady: 'Faça mais 3 testes para liberar a tendência', previousFaster: '{difference} {unit} mais rápido que o teste anterior', previousSlower: '{difference} {unit} mais lento que o teste anterior', previousTied: 'Mesmo resultado do teste anterior', calibrationNote: 'É uma estimativa do navegador, não seu elo no VALORANT. Compare testes no mesmo aparelho e com a mesma entrada.', reliabilityHigh: 'Teste confiável', reliabilityMedium: 'Estimativa útil', reliabilityLow: 'Variação alta; vale repetir', profileReason_precision: 'Cliques rápidos e consistentes combinam com uma mira mínima de precisão.', profileReason_balanced: 'Seu ritmo equilibrado combina com uma mira compacta e versátil.', profileReason_steady: 'Um centro claro ajuda a estabilizar testes com variação moderada.', profileReason_visibility: 'Uma mira mais visível reduz a procura pelo centro quando o ritmo varia.', input_mouse: 'Mouse', input_touch: 'Toque', input_pen: 'Caneta', input_keyboard: 'Teclado', input_unknown: 'Entrada', inputLabel: 'ENTRADA', historyScope: 'O histórico compara testes concluídos neste navegador.'
  }),
})

// Result sharing is loaded with CrosshairFinder instead of the site shell. This
// keeps five-language, result-only copy out of every catalog and SEO landing page.
const shareCopy = Object.freeze({
  en: Object.freeze({
    shareOpening: 'Opening system share…', shareHandoff: 'Share opened', shareCardDisclaimer: 'Browser reaction test · not an in-game rank',
    sharePanelEyebrow: 'CHALLENGE A TEAMMATE', sharePanelTitle: 'I averaged {average} {unit}. Can you beat me?', sharePanelBody: 'Open the link and start immediately. No account, setup, or long instructions.',
    sharePreviewAlt: 'Preview of your reaction result card', previewShareCard: 'Preview result card', closeSharePreview: 'Close result card preview', sharePreviewError: 'Card preview unavailable', downloadShareCard: 'Save result card',
    copyChallengeText: 'Copy challenge message', copyWorking: 'Copying…', challengeTextCopied: 'Challenge copied', shareCopySuccess: 'Challenge copied — paste it into a chat to send.', shareCopyError: 'Copy did not work. Please try again.',
    shareSystemFailed: 'System sharing did not open. Copy the challenge message or save the card instead.', shareCancelled: 'Share cancelled. Your challenge is still ready.', shareDownloadError: 'The result card could not be saved. Please try again.', shareDetailsLabel: 'Challenge details', shareWechatHint: 'Inside WeChat, copy the challenge and paste it into a friend or group chat.',
    shareCardChallengeTitle: 'I averaged {average} {unit}. Can you beat me?', shareCardChallengeHint: '3 rounds · about 10 seconds · no sign-in',
  }),
  ja: Object.freeze({
    shareOpening: '共有メニューを開いています…', shareHandoff: '共有メニューを開きました', shareCardDisclaimer: 'ブラウザ反応テスト・ゲーム内ランクではありません',
    sharePanelEyebrow: 'フレンドに挑戦', sharePanelTitle: '平均{average}{unit}。この記録を超えられる？', sharePanelBody: 'リンクを開けばすぐ挑戦できます。アカウント登録や設定は不要です。',
    sharePreviewAlt: '反応速度結果カードのプレビュー', previewShareCard: '結果カードをプレビュー', closeSharePreview: '結果カードのプレビューを閉じる', sharePreviewError: 'カードを表示できません', downloadShareCard: '結果カードを保存',
    copyChallengeText: '挑戦メッセージをコピー', copyWorking: 'コピー中…', challengeTextCopied: '挑戦をコピーしました', shareCopySuccess: '挑戦をコピーしました。チャットに貼り付けて送れます。', shareCopyError: 'コピーできませんでした。もう一度お試しください。',
    shareSystemFailed: '共有メニューを開けませんでした。メッセージのコピーまたはカード保存をお試しください。', shareCancelled: '共有をキャンセルしました。挑戦はそのまま残っています。', shareDownloadError: '結果カードを保存できませんでした。', shareDetailsLabel: '挑戦の内容', shareWechatHint: 'WeChat内では挑戦をコピーして、フレンドまたはグループチャットに貼り付けてください。',
    shareCardChallengeTitle: '平均{average}{unit}。超えられる？', shareCardChallengeHint: '3ラウンド・約10秒・ログイン不要',
  }),
  es: Object.freeze({
    shareOpening: 'Abriendo opciones del sistema…', shareHandoff: 'Opciones abiertas', shareCardDisclaimer: 'Prueba de reacción del navegador · no es rango del juego',
    sharePanelEyebrow: 'RETA A UN AMIGO', sharePanelTitle: 'Mi media fue {average} {unit}. ¿Me superas?', sharePanelBody: 'Abre el enlace y empieza al instante. Sin cuenta, configuración ni instrucciones largas.',
    sharePreviewAlt: 'Vista previa de tu tarjeta de reacción', previewShareCard: 'Ver tarjeta del resultado', closeSharePreview: 'Cerrar vista previa', sharePreviewError: 'No se pudo mostrar la tarjeta', downloadShareCard: 'Guardar tarjeta',
    copyChallengeText: 'Copiar mensaje del reto', copyWorking: 'Copiando…', challengeTextCopied: 'Reto copiado', shareCopySuccess: 'Reto copiado. Pégalo en un chat para enviarlo.', shareCopyError: 'No se pudo copiar. Inténtalo de nuevo.',
    shareSystemFailed: 'No se abrieron las opciones del sistema. Copia el reto o guarda la tarjeta.', shareCancelled: 'Has cancelado el envío. El reto sigue listo.', shareDownloadError: 'No se pudo guardar la tarjeta.', shareDetailsLabel: 'Detalles del reto', shareWechatHint: 'En WeChat, copia el reto y pégalo en un chat individual o de grupo.',
    shareCardChallengeTitle: 'Mi media fue {average} {unit}. ¿Me superas?', shareCardChallengeHint: '3 rondas · unos 10 segundos · sin iniciar sesión',
  }),
  'zh-CN': Object.freeze({
    shareOpening: '正在打开系统分享…', shareHandoff: '已打开分享', shareCardDisclaimer: '浏览器反应测试 · 不代表游戏排位',
    sharePanelEyebrow: '挑战队友', sharePanelTitle: '我三轮平均 {average} {unit}，你能更快吗？', sharePanelBody: '打开链接就能挑战，不用注册，也没有复杂设置。',
    sharePreviewAlt: '反应战绩卡预览', previewShareCard: '预览战绩卡', closeSharePreview: '关闭战绩卡预览', sharePreviewError: '战绩卡暂时无法显示', downloadShareCard: '保存战绩卡',
    copyChallengeText: '复制挑战文案', copyWorking: '正在复制…', challengeTextCopied: '挑战文案已复制', shareCopySuccess: '挑战文案已复制，粘贴到好友或群聊就能发。', shareCopyError: '复制失败，请再试一次。',
    shareSystemFailed: '系统分享没有打开，可以复制挑战文案或保存战绩卡。', shareCancelled: '已取消分享，挑战内容还在。', shareDownloadError: '战绩卡保存失败，请再试一次。', shareDetailsLabel: '挑战说明', shareWechatHint: '微信内请复制挑战文案，再粘贴到好友或群聊。',
    shareCardChallengeTitle: '我三轮平均 {average} {unit}，你能更快吗？', shareCardChallengeHint: '3 轮 · 约 10 秒 · 不用登录',
  }),
  'pt-BR': Object.freeze({
    shareOpening: 'Abrindo compartilhamento do sistema…', shareHandoff: 'Compartilhamento aberto', shareCardDisclaimer: 'Teste de reação no navegador · não é elo do jogo',
    sharePanelEyebrow: 'DESAFIE UM AMIGO', sharePanelTitle: 'Minha média foi {average} {unit}. Consegue superar?', sharePanelBody: 'Abra o link e comece na hora. Sem conta, configuração ou instruções longas.',
    sharePreviewAlt: 'Prévia do seu card de reação', previewShareCard: 'Ver card do resultado', closeSharePreview: 'Fechar prévia do card', sharePreviewError: 'Não foi possível mostrar o card', downloadShareCard: 'Salvar card',
    copyChallengeText: 'Copiar mensagem do desafio', copyWorking: 'Copiando…', challengeTextCopied: 'Desafio copiado', shareCopySuccess: 'Desafio copiado. Cole em uma conversa para enviar.', shareCopyError: 'Não foi possível copiar. Tente novamente.',
    shareSystemFailed: 'O compartilhamento do sistema não abriu. Copie o desafio ou salve o card.', shareCancelled: 'Compartilhamento cancelado. Seu desafio continua pronto.', shareDownloadError: 'Não foi possível salvar o card.', shareDetailsLabel: 'Detalhes do desafio', shareWechatHint: 'No WeChat, copie o desafio e cole em uma conversa ou grupo.',
    shareCardChallengeTitle: 'Minha média foi {average} {unit}. Consegue superar?', shareCardChallengeHint: '3 rodadas · cerca de 10 segundos · sem login',
  }),
})

export function getAimProfileCopy(locale, key, variables = {}) {
  const template = shareCopy[locale]?.[key] || refinedCopy[locale]?.[key] || aimProfileCopy[locale]?.[key] || shareCopy.en[key] || refinedCopy.en[key] || aimProfileCopy.en[key] || key
  return Object.entries(variables).reduce(
    (result, [name, value]) => result.replaceAll(`{${name}}`, String(value)),
    template,
  )
}

export const aimProfileLocales = Object.freeze(Object.keys(aimProfileCopy))
