const copy = {
  en: {
    profileEyebrow: 'YOUR AIM STYLE', profileNames: { precision: 'Precision-first', balanced: 'Balanced control', steady: 'Steady center', visibility: 'High-visibility focus' }, profileReasons: { precision: 'Your quick, consistent clicks point to a clean shape that keeps the target unobstructed.', balanced: 'Your pace and consistency suit a compact setup that can handle most fights.', steady: 'A clearly defined center should make your first click easier to repeat.', visibility: 'A stronger visual anchor should reduce the time spent finding center.' }, profileSignalsLabel: 'Aim profile signals', reactionLabel: 'Reaction', consistencyLabel: 'Variation', slotsLabel: 'Five locked crosshair slots', slotsTitle: 'Your five-slot plan', slotsBody: 'Exact picks, previews, and copy-ready codes unlock after checkout.', shortCta: 'Unlock Aim Pack', freeCatalog: 'Not ready? Browse the free catalog',
    eyebrow: 'YOUR PERSONAL LOADOUT', title: 'Unlock your 5-crosshair Aim Pack', body: 'Not five random variants: each slot covers a different fight, picked from your reaction result and play preferences.', price: '$1.99 once', priceNote: 'No subscription · final total shown by Whop', cta: 'Tune preferences & unlock', included: ['5 tailored crosshairs', 'Map previews + copy-ready codes', '2 included regenerations'], deliveryFacts: ['Instant after payment', 'No account required', 'Email recovery', 'Permanent access'], decisionNote: 'Built from your test result · five distinct situations', sampleEyebrow: 'DELIVERY PREVIEW', sampleTitle: 'One pick, shown in context', sampleBody: 'Each unlocked slot includes a map preview, why it fits, and a code you can copy.', sampleCode: '0;s;1;P;c;••••••;o;•••',
    preferenceTitle: 'Finish your profile', preferenceIntro: 'Three quick choices make the five picks meaningfully different.', modeLabel: 'What are you playing most?', visualLabel: 'How should it feel?', weaponLabel: 'Which weapon do you use most?', emailLabel: 'Where should we send your pack?', emailPlaceholder: 'you@example.com', emailHelp: 'Used only for delivery and account recovery.', emailError: 'Enter a valid delivery email.', modes: { ranked: 'Ranked', deathmatch: 'Deathmatch', fun: 'Fun modes' }, visuals: { minimal: 'Minimal', balanced: 'Balanced', visible: 'Easy to see' }, weapons: { rifle: 'Vandal / Phantom', sniper: 'Operator / Marshal', closeRange: 'SMG / Shotgun' }, continue: 'Pay $1.99 securely with Whop', checkoutFor: 'Delivering access to {email}', back: 'Back', loading: 'Preparing secure checkout…', unavailable: 'Checkout is temporarily unavailable. Your free result is still ready above.', secure: 'Secure checkout by Whop', terms: 'One-time digital purchase. Delivery is tied to your checkout email.', refundLink: 'Refund policy',
    packTitle: 'My Aim Pack', packBody: 'Your five-slot VALORANT loadout', roles: { allRound: 'All-round', closeRange: 'Close range', longRange: 'Long range', visibility: 'High visibility', fun: 'Warm-up / fun' }, copy: 'Copy code', copied: 'Copied', regenerate: 'Regenerate pack', regenerations: '{count} rebuilds left', recoveryTitle: 'Recover my Aim Pack', recoveryBody: 'Enter the email used at checkout. If a purchase exists, we will send a fresh access link.', email: 'Checkout email', send: 'Send access link', recoverySent: 'If that email has a purchase, an access link is on its way.', recoveryUnavailable: 'Automatic email recovery is not available yet. Send your Whop receipt ID to', waiting: 'Payment received in the browser. Confirming it securely…', support: 'Still waiting? Email contact@aimcodes.com with your Whop receipt ID.', previewTitle: 'Checkout preview', previewBody: 'Local preview does not call Whop. Live delivery waits for a verified payment webhook.',
  },
  'zh-CN': {
    profileEyebrow: '你的瞄准风格', profileNames: { precision: '精确优先型', balanced: '均衡控制型', steady: '稳定中心型', visibility: '高辨识聚焦型' }, profileReasons: { precision: '你的点击快且稳定，更适合不遮挡目标、中心干净的准星形态。', balanced: '你的速度和稳定性比较均衡，紧凑且能应对多数交战的配置更合适。', steady: '清楚、明确的中心点能帮助你更稳定地重复第一枪。', visibility: '更强的视觉锚点能减少寻找准星中心所花的时间。' }, profileSignalsLabel: '瞄准风格判断依据', reactionLabel: '反应速度', consistencyLabel: '波动范围', slotsLabel: '五个待解锁准星槽位', slotsTitle: '你的五槽方案', slotsBody: '完成支付后解锁具体准星、地图预览和可复制代码。', shortCta: '解锁准星包', freeCatalog: '暂不购买，浏览免费准星库',
    eyebrow: '你的专属装备组', title: '解锁 5 款个人准星包', body: '不是把同一款准星换 5 个样子：每个位置都对应不同对枪场景，结合你的测试结果和偏好生成。', price: '一次性 $1.99', priceNote: '无订阅 · 最终金额以 Whop 结账页为准', cta: '完善偏好并解锁', included: ['5 款针对性准星', '地图预览与可复制代码', '包含 2 次重新生成'], deliveryFacts: ['支付后立即生成', '无需注册账号', '支持邮箱找回', '永久访问'], decisionNote: '基于你的测试结果 · 覆盖 5 种不同场景', sampleEyebrow: '交付样例', sampleTitle: '每款准星都在场景中说明', sampleBody: '解锁后可看到地图预览、推荐理由和一键复制的完整代码。', sampleCode: '0;s;1;P;c;••••••;o;•••',
    preferenceTitle: '补全你的使用偏好', preferenceIntro: '再选 3 项，五款准星才会真正贴合你的玩法。', modeLabel: '你最常玩什么模式？', visualLabel: '你喜欢什么视觉感受？', weaponLabel: '你最常使用哪类武器？', emailLabel: '准星包发送到哪里？', emailPlaceholder: 'you@example.com', emailHelp: '仅用于交付和找回购买内容。', emailError: '请输入有效的交付邮箱。', modes: { ranked: '排位', deathmatch: '死斗', fun: '娱乐模式' }, visuals: { minimal: '极简', balanced: '均衡', visible: '醒目易找' }, weapons: { rifle: '狂徒 / 幻影', sniper: '冥驹 / 飞将', closeRange: '冲锋枪 / 霰弹枪' }, continue: '前往 Whop 支付 $1.99', checkoutFor: '购买内容将发送至 {email}', back: '返回', loading: '正在准备安全支付…', unavailable: '支付服务暂时不可用，上方免费结果仍可正常使用。', secure: '由 Whop 提供安全支付', terms: '一次性数字商品购买，交付与结账邮箱绑定。', refundLink: '退款政策',
    packTitle: '我的准星包', packBody: '为你配置的五槽无畏契约装备组', roles: { allRound: '全能主力', closeRange: '近距离', longRange: '远距离', visibility: '高可见度', fun: '热身 / 娱乐' }, copy: '复制代码', copied: '已复制', regenerate: '重新生成准星包', regenerations: '还可重新生成 {count} 次', recoveryTitle: '找回我的准星包', recoveryBody: '填写购买时使用的邮箱。如果存在订单，我们会发送新的访问链接。', email: '结账邮箱', send: '发送访问链接', recoverySent: '如果该邮箱存在订单，新的访问链接会发送到邮箱。', recoveryUnavailable: '自动邮件找回尚未启用，请将 Whop 收据编号发送至', waiting: '浏览器已完成支付，正在安全确认订单…', support: '仍未完成？请将 Whop 收据编号发送至 contact@aimcodes.com。', previewTitle: '支付预览', previewBody: '本地预览不会调用 Whop；正式交付只会在签名回调确认付款后进行。',
  },
  ja: {
    profileEyebrow: 'あなたのエイム傾向', profileNames: { precision: '精密重視タイプ', balanced: 'バランス制御タイプ', steady: '安定センタータイプ', visibility: '高視認フォーカスタイプ' }, profileReasons: { precision: '速く安定したクリックには、敵を隠さないクリーンな形が向いています。', balanced: '速度と安定性のバランスがよく、多くの場面に対応するコンパクト型が合います。', steady: 'はっきりした中心が、初弾の再現性を高めます。', visibility: '強い視覚アンカーが、中心を探す時間を減らします。' }, profileSignalsLabel: 'エイム傾向の指標', reactionLabel: '反応速度', consistencyLabel: 'ばらつき', slotsLabel: 'ロック中の5スロット', slotsTitle: '5スロットプラン', slotsBody: '決済後に具体的な候補、マッププレビュー、コピー用コードを解除します。', shortCta: 'Aim Packを解除', freeCatalog: '今は購入せず無料一覧を見る',
    eyebrow: 'パーソナルロードアウト', title: '5つのクロスヘアパックを解除', body: '同じ照準を5パターン並べるだけではありません。テスト結果と好みから、異なる交戦向けに5つを選びます。', price: '買い切り $1.99', priceNote: 'サブスクなし・最終金額はWhopで表示', cta: '好みを調整して解除', included: ['用途別クロスヘア5種', 'マッププレビューとコピー用コード', '再生成2回付き'], deliveryFacts: ['決済後すぐ生成', '登録不要', 'メールで復元', '永久アクセス'], decisionNote: 'テスト結果から作成 · 5つの異なる交戦向け', sampleEyebrow: '提供サンプル', sampleTitle: '実戦画面で各候補を確認', sampleBody: '解除後はマッププレビュー、選定理由、コピー可能なコードを確認できます。', sampleCode: '0;s;1;P;c;••••••;o;•••',
    preferenceTitle: 'プレイ傾向を仕上げる', preferenceIntro: '3つの選択で、5つの候補をあなた向けに調整します。', modeLabel: '一番遊ぶモードは？', visualLabel: '見た目の好みは？', weaponLabel: 'よく使う武器は？', emailLabel: 'パックの送信先', emailPlaceholder: 'you@example.com', emailHelp: '配信と購入内容の復元にのみ使用します。', emailError: '有効なメールアドレスを入力してください。', modes: { ranked: 'コンペティティブ', deathmatch: 'デスマッチ', fun: 'カジュアル' }, visuals: { minimal: 'ミニマル', balanced: 'バランス', visible: '見やすい' }, weapons: { rifle: 'ヴァンダル / ファントム', sniper: 'オペレーター / マーシャル', closeRange: 'SMG / ショットガン' }, continue: 'Whopで $1.99 を支払う', checkoutFor: '{email} にアクセスを送信', back: '戻る', loading: '安全な決済を準備中…', unavailable: '決済を一時的に利用できません。無料結果はそのまま使えます。', secure: 'Whopによる安全な決済', terms: '買い切りのデジタル商品です。購入メールに紐づけてお届けします。', refundLink: '返金ポリシー',
    packTitle: 'My Aim Pack', packBody: '5スロットのVALORANTロードアウト', roles: { allRound: '万能', closeRange: '近距離', longRange: '遠距離', visibility: '高視認性', fun: 'ウォームアップ' }, copy: 'コードをコピー', copied: 'コピー済み', regenerate: 'パックを再生成', regenerations: '再生成 残り{count}回', recoveryTitle: 'Aim Packを復元', recoveryBody: '購入時のメールを入力してください。購入が確認できれば新しいアクセスリンクを送ります。', email: '購入メール', send: 'アクセスリンクを送る', recoverySent: '購入が確認できる場合、新しいアクセスリンクを送信しました。', recoveryUnavailable: '自動メール復元はまだ利用できません。Whopの領収書IDをこちらへ送信してください：', waiting: '決済結果を安全に確認しています…', support: '届かない場合はWhopの領収書IDを添えて contact@aimcodes.com へ。', previewTitle: '決済プレビュー', previewBody: 'ローカルプレビューではWhopを呼び出しません。実際の提供は署名済み決済通知の確認後に行います。',
  },
  es: {
    profileEyebrow: 'TU ESTILO DE PUNTERÍA', profileNames: { precision: 'Precisión primero', balanced: 'Control equilibrado', steady: 'Centro estable', visibility: 'Enfoque muy visible' }, profileReasons: { precision: 'Tus clics rápidos y regulares apuntan a una forma limpia que no tape el objetivo.', balanced: 'Tu ritmo y regularidad encajan con una configuración compacta para casi cualquier duelo.', steady: 'Un centro bien definido debería ayudarte a repetir mejor el primer clic.', visibility: 'Un ancla visual más fuerte debería reducir el tiempo que tardas en encontrar el centro.' }, profileSignalsLabel: 'Señales del perfil de puntería', reactionLabel: 'Reacción', consistencyLabel: 'Variación', slotsLabel: 'Cinco espacios de mira bloqueados', slotsTitle: 'Tu plan de cinco miras', slotsBody: 'Las miras exactas, las vistas previas y los códigos se desbloquean después del pago.', shortCta: 'Desbloquear Aim Pack', freeCatalog: '¿Aún no? Ver el catálogo gratis',
    eyebrow: 'TU EQUIPO PERSONAL', title: 'Desbloquea tu pack de 5 miras', body: 'No son cinco variaciones al azar: cada espacio cubre un tipo de duelo, según tu reacción y preferencias.', price: 'Pago único de $1.99', priceNote: 'Sin suscripción · total final en Whop', cta: 'Ajustar y desbloquear', included: ['5 miras personalizadas', 'Vista previa en mapas y códigos listos', '2 regeneraciones incluidas'], deliveryFacts: ['Entrega inmediata', 'Sin cuenta', 'Recuperación por email', 'Acceso permanente'], decisionNote: 'Creado con tu resultado · 5 situaciones distintas', sampleEyebrow: 'VISTA DE ENTREGA', sampleTitle: 'Cada opción, en contexto', sampleBody: 'Al desbloquear verás mapa, motivo de elección y código listo para copiar.', sampleCode: '0;s;1;P;c;••••••;o;•••',
    preferenceTitle: 'Completa tu perfil', preferenceIntro: 'Tres elecciones rápidas hacen que las cinco opciones sean realmente distintas.', modeLabel: '¿Qué modo juegas más?', visualLabel: '¿Cómo quieres que se vea?', weaponLabel: '¿Qué arma usas más?', emailLabel: '¿Dónde enviamos tu pack?', emailPlaceholder: 'tu@correo.com', emailHelp: 'Solo se usa para la entrega y recuperación.', emailError: 'Introduce un correo de entrega válido.', modes: { ranked: 'Competitivo', deathmatch: 'Deathmatch', fun: 'Modos casuales' }, visuals: { minimal: 'Minimalista', balanced: 'Equilibrado', visible: 'Muy visible' }, weapons: { rifle: 'Vandal / Phantom', sniper: 'Operator / Marshal', closeRange: 'SMG / Escopeta' }, continue: 'Pagar $1.99 con Whop', checkoutFor: 'El acceso se enviará a {email}', back: 'Volver', loading: 'Preparando el pago seguro…', unavailable: 'El pago no está disponible temporalmente. Tu resultado gratuito sigue listo arriba.', secure: 'Pago seguro con Whop', terms: 'Compra digital de pago único, vinculada al correo del pago.', refundLink: 'Política de reembolso',
    packTitle: 'Mi Aim Pack', packBody: 'Tu equipo VALORANT de cinco miras', roles: { allRound: 'Uso general', closeRange: 'Corta distancia', longRange: 'Larga distancia', visibility: 'Alta visibilidad', fun: 'Calentamiento / diversión' }, copy: 'Copiar código', copied: 'Copiado', regenerate: 'Regenerar pack', regenerations: 'Quedan {count} regeneraciones', recoveryTitle: 'Recuperar mi Aim Pack', recoveryBody: 'Escribe el correo usado al pagar. Si existe una compra, enviaremos un nuevo enlace de acceso.', email: 'Correo de pago', send: 'Enviar enlace', recoverySent: 'Si ese correo tiene una compra, el enlace ya está en camino.', recoveryUnavailable: 'La recuperación automática por correo aún no está disponible. Envía el ID de tu recibo de Whop a', waiting: 'Pago recibido. Lo estamos verificando de forma segura…', support: '¿Sigue pendiente? Envía tu recibo de Whop a contact@aimcodes.com.', previewTitle: 'Vista previa del pago', previewBody: 'La vista local no llama a Whop. La entrega real espera un webhook de pago verificado.',
  },
  'pt-BR': {
    profileEyebrow: 'SEU ESTILO DE MIRA', profileNames: { precision: 'Precisão em primeiro lugar', balanced: 'Controle equilibrado', steady: 'Centro estável', visibility: 'Foco de alta visibilidade' }, profileReasons: { precision: 'Cliques rápidos e consistentes combinam com um formato limpo que não cobre o alvo.', balanced: 'Seu ritmo e consistência pedem uma configuração compacta para a maioria dos duelos.', steady: 'Um centro bem definido ajuda a repetir o primeiro clique com mais estabilidade.', visibility: 'Uma âncora visual mais forte reduz o tempo gasto procurando o centro.' }, profileSignalsLabel: 'Sinais do perfil de mira', reactionLabel: 'Reação', consistencyLabel: 'Variação', slotsLabel: 'Cinco espaços de mira bloqueados', slotsTitle: 'Seu plano de cinco miras', slotsBody: 'As escolhas exatas, prévias e códigos prontos são liberados após o pagamento.', shortCta: 'Desbloquear Aim Pack', freeCatalog: 'Ainda não? Ver o catálogo grátis',
    eyebrow: 'SEU LOADOUT PESSOAL', title: 'Desbloqueie seu pacote com 5 miras', body: 'Não são cinco variações aleatórias: cada espaço serve a um tipo de duelo, com base no seu resultado e preferências.', price: 'Pagamento único de US$ 1,99', priceNote: 'Sem assinatura · total final na Whop', cta: 'Ajustar e desbloquear', included: ['5 miras personalizadas', 'Prévia nos mapas e códigos prontos', '2 novas gerações incluídas'], deliveryFacts: ['Entrega imediata', 'Sem cadastro', 'Recuperação por e-mail', 'Acesso permanente'], decisionNote: 'Criado pelo seu resultado · 5 situações diferentes', sampleEyebrow: 'PRÉVIA DA ENTREGA', sampleTitle: 'Cada escolha em contexto', sampleBody: 'Após liberar, você vê mapa, motivo da escolha e código pronto para copiar.', sampleCode: '0;s;1;P;c;••••••;o;•••',
    preferenceTitle: 'Complete seu perfil', preferenceIntro: 'Três escolhas rápidas tornam as cinco opções realmente pessoais.', modeLabel: 'Qual modo você mais joga?', visualLabel: 'Como a mira deve parecer?', weaponLabel: 'Qual arma você mais usa?', emailLabel: 'Para onde enviamos o pacote?', emailPlaceholder: 'voce@email.com', emailHelp: 'Usado somente para entrega e recuperação.', emailError: 'Digite um e-mail de entrega válido.', modes: { ranked: 'Competitivo', deathmatch: 'Mata-mata', fun: 'Modos casuais' }, visuals: { minimal: 'Minimalista', balanced: 'Equilibrada', visible: 'Bem visível' }, weapons: { rifle: 'Vandal / Phantom', sniper: 'Operator / Marshal', closeRange: 'SMG / Escopeta' }, continue: 'Pagar US$ 1,99 com Whop', checkoutFor: 'O acesso será enviado para {email}', back: 'Voltar', loading: 'Preparando o pagamento seguro…', unavailable: 'O pagamento está temporariamente indisponível. Seu resultado gratuito continua disponível acima.', secure: 'Pagamento seguro com Whop', terms: 'Compra digital única, vinculada ao e-mail usado no pagamento.', refundLink: 'Política de reembolso',
    packTitle: 'Meu Aim Pack', packBody: 'Seu loadout de cinco miras para VALORANT', roles: { allRound: 'Uso geral', closeRange: 'Curta distância', longRange: 'Longa distância', visibility: 'Alta visibilidade', fun: 'Aquecimento / diversão' }, copy: 'Copiar código', copied: 'Copiado', regenerate: 'Gerar novo pacote', regenerations: 'Restam {count} novas gerações', recoveryTitle: 'Recuperar meu Aim Pack', recoveryBody: 'Digite o e-mail usado no pagamento. Se houver uma compra, enviaremos um novo link de acesso.', email: 'E-mail do pagamento', send: 'Enviar link', recoverySent: 'Se houver uma compra nesse e-mail, o link já está a caminho.', recoveryUnavailable: 'A recuperação automática por e-mail ainda não está disponível. Envie o ID do recibo da Whop para', waiting: 'Pagamento recebido. Estamos confirmando com segurança…', support: 'Ainda aguardando? Envie o recibo da Whop para contact@aimcodes.com.', previewTitle: 'Prévia do pagamento', previewBody: 'A prévia local não chama a Whop. A entrega real aguarda um webhook de pagamento verificado.',
  },
}

const fallback = copy.en

export function paidPackCopy(locale) {
  return copy[locale] || fallback
}
