const copy = {
  en: {
    eyebrow: 'YOUR PERSONAL LOADOUT', title: 'Unlock your 5-crosshair Aim Pack', body: 'Five different jobs, picked from your reaction result. One payment, long-term access, and two fresh rebuilds included.', price: '$1.99 once', cta: 'Build my Aim Pack', included: ['5 tailored crosshairs', 'Map previews + copy-ready codes', '2 included regenerations'],
    preferenceTitle: 'Tune the pack', modeLabel: 'What are you playing most?', visualLabel: 'How should it feel?', emailLabel: 'Where should we send your pack?', emailPlaceholder: 'you@example.com', emailHelp: 'Used only for delivery and account recovery.', emailError: 'Enter a valid delivery email.', modes: { ranked: 'Ranked', deathmatch: 'Deathmatch', fun: 'Fun modes' }, visuals: { minimal: 'Minimal', balanced: 'Balanced', visible: 'Easy to see' }, continue: 'Continue to secure checkout', back: 'Back', loading: 'Preparing secure checkout…', unavailable: 'Checkout is temporarily unavailable. Your free result is still ready above.', secure: 'Secure checkout by Whop', terms: 'One-time digital purchase. Delivery is tied to your checkout email.', refundLink: 'Refund policy',
    packTitle: 'My Aim Pack', packBody: 'Your five-slot VALORANT loadout', roles: { allRound: 'All-round', closeRange: 'Close range', longRange: 'Long range', visibility: 'High visibility', fun: 'Warm-up / fun' }, copy: 'Copy code', copied: 'Copied', regenerate: 'Regenerate pack', regenerations: '{count} rebuilds left', recoveryTitle: 'Recover my Aim Pack', recoveryBody: 'Enter the email used at checkout. If a purchase exists, we will send a fresh access link.', email: 'Checkout email', send: 'Send access link', recoverySent: 'If that email has a purchase, an access link is on its way.', recoveryUnavailable: 'Automatic email recovery is not available yet. Send your Whop receipt ID to', waiting: 'Payment received in the browser. Confirming it securely…', support: 'Still waiting? Email contact@aimcodes.com with your Whop receipt ID.', previewTitle: 'Checkout preview', previewBody: 'Local preview does not call Whop. Live delivery waits for a verified payment webhook.',
  },
  'zh-CN': {
    eyebrow: '你的专属装备组', title: '解锁 5 款个人准星包', body: '根据反应测试结果，为五种场景分别挑选准星。一次付费，长期访问，并含 2 次重新生成。', price: '一次性 $1.99', cta: '生成我的准星包', included: ['5 款针对性准星', '地图预览与可复制代码', '包含 2 次重新生成'],
    preferenceTitle: '再调一下偏好', modeLabel: '你最常玩什么模式？', visualLabel: '你喜欢什么视觉感受？', emailLabel: '准星包发送到哪里？', emailPlaceholder: 'you@example.com', emailHelp: '仅用于交付和找回购买内容。', emailError: '请输入有效的交付邮箱。', modes: { ranked: '排位', deathmatch: '死斗', fun: '娱乐模式' }, visuals: { minimal: '极简', balanced: '均衡', visible: '醒目易找' }, continue: '继续安全支付', back: '返回', loading: '正在准备安全支付…', unavailable: '支付服务暂时不可用，上方免费结果仍可正常使用。', secure: '由 Whop 提供安全支付', terms: '一次性数字商品购买，交付与结账邮箱绑定。', refundLink: '退款政策',
    packTitle: '我的准星包', packBody: '为你配置的五槽无畏契约装备组', roles: { allRound: '全能主力', closeRange: '近距离', longRange: '远距离', visibility: '高可见度', fun: '热身 / 娱乐' }, copy: '复制代码', copied: '已复制', regenerate: '重新生成准星包', regenerations: '还可重新生成 {count} 次', recoveryTitle: '找回我的准星包', recoveryBody: '填写购买时使用的邮箱。如果存在订单，我们会发送新的访问链接。', email: '结账邮箱', send: '发送访问链接', recoverySent: '如果该邮箱存在订单，新的访问链接会发送到邮箱。', recoveryUnavailable: '自动邮件找回尚未启用，请将 Whop 收据编号发送至', waiting: '浏览器已完成支付，正在安全确认订单…', support: '仍未完成？请将 Whop 收据编号发送至 contact@aimcodes.com。', previewTitle: '支付预览', previewBody: '本地预览不会调用 Whop；正式交付只会在签名回调确认付款后进行。',
  },
  ja: {
    eyebrow: 'パーソナルロードアウト', title: '5つのクロスヘアパックを解除', body: '反応速度の結果から5つの用途に合わせて選びます。買い切り、長期アクセス、再生成2回付き。', price: '買い切り $1.99', cta: 'Aim Packを作る', included: ['用途別クロスヘア5種', 'マッププレビューとコピー用コード', '再生成2回付き'],
    preferenceTitle: '好みを調整', modeLabel: '一番遊ぶモードは？', visualLabel: '見た目の好みは？', emailLabel: 'パックの送信先', emailPlaceholder: 'you@example.com', emailHelp: '配信と購入内容の復元にのみ使用します。', emailError: '有効なメールアドレスを入力してください。', modes: { ranked: 'コンペティティブ', deathmatch: 'デスマッチ', fun: 'カジュアル' }, visuals: { minimal: 'ミニマル', balanced: 'バランス', visible: '見やすい' }, continue: '安全な決済へ', back: '戻る', loading: '安全な決済を準備中…', unavailable: '決済を一時的に利用できません。無料結果はそのまま使えます。', secure: 'Whopによる安全な決済', terms: '買い切りのデジタル商品です。購入メールに紐づけてお届けします。', refundLink: '返金ポリシー',
    packTitle: 'My Aim Pack', packBody: '5スロットのVALORANTロードアウト', roles: { allRound: '万能', closeRange: '近距離', longRange: '遠距離', visibility: '高視認性', fun: 'ウォームアップ' }, copy: 'コードをコピー', copied: 'コピー済み', regenerate: 'パックを再生成', regenerations: '再生成 残り{count}回', recoveryTitle: 'Aim Packを復元', recoveryBody: '購入時のメールを入力してください。購入が確認できれば新しいアクセスリンクを送ります。', email: '購入メール', send: 'アクセスリンクを送る', recoverySent: '購入が確認できる場合、新しいアクセスリンクを送信しました。', recoveryUnavailable: '自動メール復元はまだ利用できません。Whopの領収書IDをこちらへ送信してください：', waiting: '決済結果を安全に確認しています…', support: '届かない場合はWhopの領収書IDを添えて contact@aimcodes.com へ。', previewTitle: '決済プレビュー', previewBody: 'ローカルプレビューではWhopを呼び出しません。実際の提供は署名済み決済通知の確認後に行います。',
  },
  es: {
    eyebrow: 'TU EQUIPO PERSONAL', title: 'Desbloquea tu pack de 5 miras', body: 'Cinco miras para distintos usos, elegidas según tu resultado de reacción. Un solo pago, acceso a largo plazo y dos regeneraciones incluidas.', price: 'Pago único de $1.99', cta: 'Crear mi Aim Pack', included: ['5 miras personalizadas', 'Vista previa en mapas y códigos listos', '2 regeneraciones incluidas'],
    preferenceTitle: 'Ajusta tu pack', modeLabel: '¿Qué modo juegas más?', visualLabel: '¿Cómo quieres que se vea?', emailLabel: '¿Dónde enviamos tu pack?', emailPlaceholder: 'tu@correo.com', emailHelp: 'Solo se usa para la entrega y recuperación.', emailError: 'Introduce un correo de entrega válido.', modes: { ranked: 'Competitivo', deathmatch: 'Deathmatch', fun: 'Modos casuales' }, visuals: { minimal: 'Minimalista', balanced: 'Equilibrado', visible: 'Muy visible' }, continue: 'Continuar al pago seguro', back: 'Volver', loading: 'Preparando el pago seguro…', unavailable: 'El pago no está disponible temporalmente. Tu resultado gratuito sigue listo arriba.', secure: 'Pago seguro con Whop', terms: 'Compra digital de pago único, vinculada al correo del pago.', refundLink: 'Política de reembolso',
    packTitle: 'Mi Aim Pack', packBody: 'Tu equipo VALORANT de cinco miras', roles: { allRound: 'Uso general', closeRange: 'Corta distancia', longRange: 'Larga distancia', visibility: 'Alta visibilidad', fun: 'Calentamiento / diversión' }, copy: 'Copiar código', copied: 'Copiado', regenerate: 'Regenerar pack', regenerations: 'Quedan {count} regeneraciones', recoveryTitle: 'Recuperar mi Aim Pack', recoveryBody: 'Escribe el correo usado al pagar. Si existe una compra, enviaremos un nuevo enlace de acceso.', email: 'Correo de pago', send: 'Enviar enlace', recoverySent: 'Si ese correo tiene una compra, el enlace ya está en camino.', recoveryUnavailable: 'La recuperación automática por correo aún no está disponible. Envía el ID de tu recibo de Whop a', waiting: 'Pago recibido. Lo estamos verificando de forma segura…', support: '¿Sigue pendiente? Envía tu recibo de Whop a contact@aimcodes.com.', previewTitle: 'Vista previa del pago', previewBody: 'La vista local no llama a Whop. La entrega real espera un webhook de pago verificado.',
  },
  'pt-BR': {
    eyebrow: 'SEU LOADOUT PESSOAL', title: 'Desbloqueie seu pacote com 5 miras', body: 'Cinco miras para funções diferentes, escolhidas pelo seu resultado de reação. Pagamento único, acesso de longo prazo e duas novas gerações incluídas.', price: 'Pagamento único de US$ 1,99', cta: 'Criar meu Aim Pack', included: ['5 miras personalizadas', 'Prévia nos mapas e códigos prontos', '2 novas gerações incluídas'],
    preferenceTitle: 'Ajuste o pacote', modeLabel: 'Qual modo você mais joga?', visualLabel: 'Como a mira deve parecer?', emailLabel: 'Para onde enviamos o pacote?', emailPlaceholder: 'voce@email.com', emailHelp: 'Usado somente para entrega e recuperação.', emailError: 'Digite um e-mail de entrega válido.', modes: { ranked: 'Competitivo', deathmatch: 'Mata-mata', fun: 'Modos casuais' }, visuals: { minimal: 'Minimalista', balanced: 'Equilibrada', visible: 'Bem visível' }, continue: 'Continuar para o pagamento seguro', back: 'Voltar', loading: 'Preparando o pagamento seguro…', unavailable: 'O pagamento está temporariamente indisponível. Seu resultado gratuito continua disponível acima.', secure: 'Pagamento seguro com Whop', terms: 'Compra digital única, vinculada ao e-mail usado no pagamento.', refundLink: 'Política de reembolso',
    packTitle: 'Meu Aim Pack', packBody: 'Seu loadout de cinco miras para VALORANT', roles: { allRound: 'Uso geral', closeRange: 'Curta distância', longRange: 'Longa distância', visibility: 'Alta visibilidade', fun: 'Aquecimento / diversão' }, copy: 'Copiar código', copied: 'Copiado', regenerate: 'Gerar novo pacote', regenerations: 'Restam {count} novas gerações', recoveryTitle: 'Recuperar meu Aim Pack', recoveryBody: 'Digite o e-mail usado no pagamento. Se houver uma compra, enviaremos um novo link de acesso.', email: 'E-mail do pagamento', send: 'Enviar link', recoverySent: 'Se houver uma compra nesse e-mail, o link já está a caminho.', recoveryUnavailable: 'A recuperação automática por e-mail ainda não está disponível. Envie o ID do recibo da Whop para', waiting: 'Pagamento recebido. Estamos confirmando com segurança…', support: 'Ainda aguardando? Envie o recibo da Whop para contact@aimcodes.com.', previewTitle: 'Prévia do pagamento', previewBody: 'A prévia local não chama a Whop. A entrega real aguarda um webhook de pagamento verificado.',
  },
}

const fallback = copy.en

export function paidPackCopy(locale) {
  return copy[locale] || fallback
}
