import { crosshairStatistics } from '../data/catalogStatistics.js'

const total = crosshairStatistics.total

const content = Object.freeze({
  en: Object.freeze({
    navLabel: 'Crosshair statistics',
    eyebrow: 'AIMCODES DATA SNAPSHOT',
    title: `${total} VALORANT crosshair codes analyzed`,
    intro: `Explore color, shape and collection patterns across the ${total} crosshair pages currently published by AimCodes. Every count comes from a code you can open, preview and copy.`,
    summaryTitle: 'What the data says',
    summary: `White, cyan and red account for most of the published catalog. Classic line crosshairs are the largest shape group, while dot and small crosshairs remain substantial alternatives. These numbers describe the AimCodes library, not every VALORANT player.`,
    metrics: Object.freeze({ published: 'Published codes', pros: 'Pro player codes', colors: 'Color groups', largest: 'Largest collection' }),
    colorTitle: 'Crosshair colors in the library',
    colorIntro: 'Counts use each page’s primary display color. Custom shades are grouped with their closest named color when the catalog provides one.',
    categoryTitle: 'Crosshair shape groups',
    categoryIntro: 'Each code has one primary shape group so the totals do not overlap.',
    collectionTitle: 'Collections players can browse now',
    collectionIntro: 'Collections can overlap because one crosshair may be funny, small and outlined at the same time.',
    table: Object.freeze({ group: 'Group', codes: 'Codes', share: 'Share of published pages', open: 'Browse collection' }),
    colors: Object.freeze({ white: 'White', cyan: 'Cyan', red: 'Red', pink: 'Pink', green: 'Green', yellow: 'Yellow', black: 'Black', custom: 'Custom' }),
    categories: Object.freeze({ classic: 'Classic line crosshairs', fun: 'Funny and experimental', small: 'Small crosshairs', dot: 'Dot crosshairs', cute: 'Cute shapes' }),
    methodologyTitle: 'How this snapshot is calculated',
    methodology: `AimCodes counts only canonical, indexable crosshair detail pages. Counts are rebuilt from the current catalog during deployment. Collection totals overlap and should not be added together. The snapshot measures the AimCodes catalog, not global usage or win rate.`,
    sections: Object.freeze([
      Object.freeze({ title: 'What this dataset includes', paragraphs: Object.freeze([`The snapshot covers ${total} published crosshair pages with working profile codes. Each page has a preview, copy action and its own canonical URL.`, 'Draft, duplicate and noindex pages are excluded, so every counted item has a page that players and search engines can actually open.']), bullets: Object.freeze(['One count per canonical crosshair page.', 'Primary color and shape come from the catalog record.', 'Collection counts are calculated from the live collection membership.']) }),
      Object.freeze({ title: 'What these numbers do not prove', paragraphs: Object.freeze(['A large catalog group does not mean it is the most popular or the best-performing setup. The library reflects what AimCodes has published and organized.', 'Use the distribution to find options worth testing, then judge visibility and comfort on your own maps and display.']), bullets: Object.freeze(['Catalog share is not player usage share.', 'A pro player code is not automatically the best code for you.', 'Crosshair choice does not replace movement, placement or recoil practice.']) }),
      Object.freeze({ title: 'Turn the data into a useful shortlist', paragraphs: Object.freeze(['Start with the color or shape group that solves your current problem. If you lose the center, browse cyan, white or small crosshairs; if you want a memorable casual setup, open the funny collection.', 'Preview a few options on the same scene and change only one variable at a time. Copy the winner after it stays readable on both bright and dark areas.']), bullets: Object.freeze(['Pick one intent: visibility, precision or fun.', 'Compare on the same map scene.', 'Keep two finalists and test them in the range.']) }),
    ]),
    faq: Object.freeze([
      Object.freeze(['How many VALORANT crosshairs are on AimCodes?', `This snapshot counts ${total} canonical, indexable crosshair pages. The number is rebuilt from the live catalog when the site is deployed.`]),
      Object.freeze(['What is the most common color in this dataset?', 'White is currently the largest named color group, followed closely by cyan and red. This is a catalog distribution, not a claim about all players.']),
      Object.freeze(['Can one crosshair appear in more than one collection?', 'Yes. A code can fit several useful filters, such as small, one-tap and crosshairs without outlines. Shape and color totals do not overlap within their own tables.']),
    ]),
    recommendedCrosshairIds: Object.freeze(['tenz', 'demon1', 'forsaken', 'cat-pink']),
    relatedArticleKeys: Object.freeze(['colors', 'dotVsCross', 'settings']),
    relatedCollectionKeys: Object.freeze(['funny', 'small', 'dot', 'pro']),
    relatedToolKeys: Object.freeze(['comparison', 'generator']),
    cta: 'Open a crosshair from the dataset',
    metaTitle: `${total} VALORANT Crosshairs Analyzed: Colors & Shapes | AimCodes`,
    metaDescription: `Explore live statistics from ${total} AimCodes VALORANT crosshair pages, including color, shape and collection counts with previews and working codes.`,
  }),
  es: Object.freeze({
    navLabel: 'Estadísticas de miras', eyebrow: 'DATOS DE AIMCODES', title: `${total} códigos de mira de VALORANT analizados`,
    intro: `Consulta patrones de color, forma y colección en las ${total} páginas de miras publicadas actualmente en AimCodes. Cada cifra corresponde a un código que puedes abrir, probar y copiar.`,
    summaryTitle: 'Qué muestran los datos', summary: 'Blanco, cian y rojo reúnen la mayor parte del catálogo publicado. Las miras clásicas de líneas son el grupo más grande, con muchas alternativas de punto y miras pequeñas. Los datos describen AimCodes, no a todos los jugadores.',
    metrics: Object.freeze({ published: 'Códigos publicados', pros: 'Códigos de pros', colors: 'Grupos de color', largest: 'Colección mayor' }),
    colorTitle: 'Colores del catálogo', colorIntro: 'Contamos el color principal de cada página. Los tonos personalizados se agrupan con el color nombrado más cercano cuando el catálogo lo indica.',
    categoryTitle: 'Grupos de formas', categoryIntro: 'Cada código tiene un solo grupo de forma principal, así que estos totales no se solapan.',
    collectionTitle: 'Colecciones disponibles', collectionIntro: 'Las colecciones sí pueden solaparse: una mira puede ser divertida, pequeña y tener contorno a la vez.',
    table: Object.freeze({ group: 'Grupo', codes: 'Códigos', share: 'Porcentaje de páginas', open: 'Ver colección' }),
    colors: Object.freeze({ white: 'Blanco', cyan: 'Cian', red: 'Rojo', pink: 'Rosa', green: 'Verde', yellow: 'Amarillo', black: 'Negro', custom: 'Personalizado' }),
    categories: Object.freeze({ classic: 'Miras clásicas de líneas', fun: 'Divertidas y experimentales', small: 'Miras pequeñas', dot: 'Miras de punto', cute: 'Formas adorables' }),
    methodologyTitle: 'Cómo calculamos esta foto del catálogo', methodology: 'AimCodes cuenta solo páginas de mira canónicas e indexables. Los datos se reconstruyen desde el catálogo en cada publicación. Las colecciones se solapan y no deben sumarse. No representan el uso ni el rendimiento global de los jugadores.',
    sections: Object.freeze([
      Object.freeze({ title: 'Qué incluye el conjunto de datos', paragraphs: Object.freeze([`Incluye ${total} páginas publicadas con código de perfil, vista previa, botón de copia y URL canónica.`, 'Las páginas borrador, duplicadas o noindex quedan fuera del recuento.']), bullets: Object.freeze(['Una unidad por página canónica.', 'Color y forma salen del registro del catálogo.', 'Las colecciones se calculan con sus miembros actuales.']) }),
      Object.freeze({ title: 'Qué no demuestran estas cifras', paragraphs: Object.freeze(['Un grupo grande no significa que sea el más popular ni el que mejor rinde. Solo muestra cómo está compuesto el catálogo.', 'Úsalo para crear una lista corta y comprueba la visibilidad en tus mapas y monitor.']), bullets: Object.freeze(['Cuota del catálogo no es cuota de uso.', 'Una mira profesional no es automáticamente la mejor para ti.', 'La mira no sustituye colocación, movimiento o control del retroceso.']) }),
      Object.freeze({ title: 'Convierte los datos en una lista útil', paragraphs: Object.freeze(['Elige primero el problema: visibilidad, precisión o diversión. Después abre el grupo de color o forma que lo resuelve.', 'Compara varias opciones en la misma escena y cambia una sola variable cada vez.']), bullets: Object.freeze(['Define una intención.', 'Usa la misma escena.', 'Prueba dos finalistas en el campo de tiro.']) }),
    ]),
    faq: Object.freeze([Object.freeze(['¿Cuántas miras hay en AimCodes?', `Esta foto cuenta ${total} páginas canónicas e indexables y se actualiza desde el catálogo al publicar.`]), Object.freeze(['¿Cuál es el color más común?', 'El blanco es el grupo más grande, seguido de cerca por cian y rojo. Es una distribución del catálogo, no de todos los jugadores.']), Object.freeze(['¿Una mira puede estar en varias colecciones?', 'Sí. Puede ser pequeña, de one-tap y sin contorno a la vez. Las tablas de color y forma no se solapan dentro de cada grupo.'])]),
    recommendedCrosshairIds: Object.freeze(['tenz', 'demon1', 'forsaken', 'cat-pink']), relatedArticleKeys: Object.freeze(['colors', 'dotVsCross', 'settings']), relatedCollectionKeys: Object.freeze(['funny', 'small', 'dot', 'pro']), relatedToolKeys: Object.freeze(['comparison', 'generator']), cta: 'Abrir una mira del conjunto',
    metaTitle: `${total} miras de VALORANT analizadas: colores y formas | AimCodes`, metaDescription: `Consulta estadísticas de ${total} miras de AimCodes: colores, formas y colecciones, con vista previa y códigos utilizables.`,
  }),
  'pt-BR': Object.freeze({
    navLabel: 'Estatísticas de miras', eyebrow: 'DADOS DO AIMCODES', title: `${total} códigos de mira do VALORANT analisados`, intro: `Veja padrões de cor, formato e coleção nas ${total} páginas de miras publicadas no AimCodes. Cada número vem de um código que você pode abrir, testar e copiar.`,
    summaryTitle: 'O que os dados mostram', summary: 'Branco, ciano e vermelho formam a maior parte do catálogo publicado. Miras clássicas de linhas são o maior grupo, com muitas opções de ponto e miras pequenas. Os números descrevem o AimCodes, não todos os jogadores.',
    metrics: Object.freeze({ published: 'Códigos publicados', pros: 'Códigos de pros', colors: 'Grupos de cor', largest: 'Maior coleção' }), colorTitle: 'Cores no catálogo', colorIntro: 'Contamos a cor principal de cada página. Tons personalizados entram na cor nomeada mais próxima quando o catálogo informa essa relação.', categoryTitle: 'Grupos de formato', categoryIntro: 'Cada código tem um único formato principal, então estes totais não se sobrepõem.', collectionTitle: 'Coleções para navegar agora', collectionIntro: 'Coleções podem se sobrepor: uma mira pode ser divertida, pequena e ter contorno ao mesmo tempo.', table: Object.freeze({ group: 'Grupo', codes: 'Códigos', share: 'Parcela das páginas', open: 'Abrir coleção' }), colors: Object.freeze({ white: 'Branco', cyan: 'Ciano', red: 'Vermelho', pink: 'Rosa', green: 'Verde', yellow: 'Amarelo', black: 'Preto', custom: 'Personalizado' }), categories: Object.freeze({ classic: 'Miras clássicas de linhas', fun: 'Divertidas e experimentais', small: 'Miras pequenas', dot: 'Miras de ponto', cute: 'Formatos fofos' }), methodologyTitle: 'Como calculamos este retrato', methodology: 'O AimCodes conta apenas páginas canônicas e indexáveis. Os números são recalculados a partir do catálogo em cada publicação. Coleções se sobrepõem e não devem ser somadas. Isto não mede uso global nem taxa de vitória.',
    sections: Object.freeze([Object.freeze({ title: 'O que o conjunto inclui', paragraphs: Object.freeze([`São ${total} páginas publicadas com código, prévia, botão de copiar e URL canônica.`, 'Rascunhos, duplicatas e páginas noindex ficam fora.']), bullets: Object.freeze(['Uma contagem por página canônica.', 'Cor e formato vêm do catálogo.', 'Coleções usam os membros publicados hoje.']) }), Object.freeze({ title: 'O que os números não provam', paragraphs: Object.freeze(['Um grupo maior não é necessariamente mais popular ou melhor. Ele apenas mostra a composição do catálogo.', 'Use os dados para montar uma lista curta e teste a visibilidade no seu mapa e monitor.']), bullets: Object.freeze(['Participação no catálogo não é participação de uso.', 'Mira de pro não é automaticamente a melhor para você.', 'A mira não substitui posicionamento, movimento ou controle de recuo.']) }), Object.freeze({ title: 'Transforme os dados numa lista útil', paragraphs: Object.freeze(['Comece pelo problema: visibilidade, precisão ou diversão. Abra o grupo que melhor resolve isso.', 'Compare no mesmo cenário e mude apenas uma variável por vez.']), bullets: Object.freeze(['Escolha uma intenção.', 'Use a mesma cena.', 'Teste duas finalistas no treino.']) })]),
    faq: Object.freeze([Object.freeze(['Quantas miras existem no AimCodes?', `Este retrato conta ${total} páginas canônicas e indexáveis, recalculadas do catálogo a cada publicação.`]), Object.freeze(['Qual é a cor mais comum?', 'Branco é o maior grupo, seguido de perto por ciano e vermelho. É uma distribuição do catálogo, não de todos os jogadores.']), Object.freeze(['Uma mira pode estar em mais de uma coleção?', 'Sim. Ela pode ser pequena, de one-tap e sem contorno ao mesmo tempo. As tabelas de cor e formato não se sobrepõem internamente.'])]), recommendedCrosshairIds: Object.freeze(['tenz', 'demon1', 'forsaken', 'cat-pink']), relatedArticleKeys: Object.freeze(['colors', 'dotVsCross', 'settings']), relatedCollectionKeys: Object.freeze(['funny', 'small', 'dot', 'pro']), relatedToolKeys: Object.freeze(['comparison', 'generator']), cta: 'Abrir uma mira do conjunto', metaTitle: `${total} miras do VALORANT analisadas: cores e formatos | AimCodes`, metaDescription: `Veja estatísticas de ${total} miras do AimCodes: cores, formatos e coleções, com prévias e códigos que funcionam.`,
  }),
  'zh-CN': Object.freeze({
    navLabel: '准星数据统计', eyebrow: 'AIMCODES 准星数据', title: `${total} 个无畏契约准星代码数据统计`, intro: `看看 AimCodes 当前公开的 ${total} 个准星页面里，颜色、形状和合集分别是怎么分布的。每一个数字都对应能打开、预览和复制的真实准星代码。`,
    summaryTitle: '数据先说结论', summary: '白色、青色和红色占了公开准星库的大部分；传统线条准星数量最多，小准星和圆点准星也有足够多的选择。这里统计的是 AimCodes 准星库，不代表所有玩家的使用率。',
    metrics: Object.freeze({ published: '公开准星代码', pros: '职业选手准星', colors: '颜色分类', largest: '最大准星合集' }), colorTitle: '准星颜色分布', colorIntro: '每个页面只按主要显示颜色统计一次；有明确对应关系的自定义色会归到最接近的常用颜色。', categoryTitle: '准星形状分布', categoryIntro: '每个代码只有一个主要形状分类，因此这里的总数不会重复。', collectionTitle: '现在可以直接浏览的合集', collectionIntro: '合集允许重复：同一个准星可以同时属于趣味、小型和带轮廓等多个合集。', table: Object.freeze({ group: '分类', codes: '代码数量', share: '占公开页面比例', open: '打开合集' }), colors: Object.freeze({ white: '白色', cyan: '青色', red: '红色', pink: '粉色', green: '绿色', yellow: '黄色', black: '黑色', custom: '自定义' }), categories: Object.freeze({ classic: '传统线条准星', fun: '趣味与实验型准星', small: '小准星', dot: '圆点准星', cute: '可爱造型准星' }), methodologyTitle: '这些数字是怎么算出来的', methodology: 'AimCodes 只统计拥有独立规范网址、允许索引的准星详情页。每次发布时都会根据当前准星库重新计算。多个合集之间会重复，不能直接相加；这些数字也不等于全体玩家使用率或胜率。',
    sections: Object.freeze([Object.freeze({ title: '这份数据包含什么', paragraphs: Object.freeze([`统计范围是 ${total} 个已经公开的准星页面，每页都有可用代码、地图预览、复制按钮和独立网址。`, '草稿、重复页和 noindex 页面都不会计入，因此每个数字都能落到玩家和搜索引擎可以打开的页面。']), bullets: Object.freeze(['每个规范准星页面只统计一次。', '主要颜色和形状来自准星库记录。', '合集数量按当前实际成员计算。']) }), Object.freeze({ title: '这些数字不能说明什么', paragraphs: Object.freeze(['某一类数量多，不代表它更热门或更强，只代表 AimCodes 当前收集和整理的内容结构。', '可以用分布快速缩小选择，再到自己常玩的地图和显示器上测试清晰度。']), bullets: Object.freeze(['准星库占比不等于玩家使用率。', '职业选手准星不一定最适合你。', '换准星不能代替预瞄、停枪和压枪练习。']) }), Object.freeze({ title: '怎么用数据快速挑准星', paragraphs: Object.freeze(['先确定你要解决的是看不清、打头不准，还是只想找一个有趣的造型，然后打开对应的颜色或形状合集。', '在同一张地图场景里比较几个候选，每次只改一个变量；亮处和暗处都清楚，再复制进游戏。']), bullets: Object.freeze(['先选目标：清晰、精准或有趣。', '固定同一张地图场景。', '留下两个候选去训练场实测。']) })]),
    faq: Object.freeze([Object.freeze(['AimCodes 现在有多少个准星？', `这份统计包含 ${total} 个拥有独立规范网址、允许索引的准星页面；每次网站发布都会按当前准星库重新计算。`]), Object.freeze(['这份数据里哪种颜色最多？', '白色目前最多，青色和红色非常接近。它只是 AimCodes 准星库的分布，不代表全部玩家。']), Object.freeze(['一个准星会同时出现在多个合集中吗？', '会，例如同一个代码可以同时属于小准星、单点准星和无轮廓准星。颜色表和形状表内部不会重复统计。'])]), recommendedCrosshairIds: Object.freeze(['tenz', 'demon1', 'forsaken', 'cat-pink']), relatedArticleKeys: Object.freeze(['colors', 'dotVsCross', 'settings']), relatedCollectionKeys: Object.freeze(['funny', 'small', 'dot', 'pro']), relatedToolKeys: Object.freeze(['comparison', 'generator']), cta: '从数据里挑一个准星', metaTitle: `${total} 个无畏契约准星数据统计：颜色与形状 | AimCodes`, metaDescription: `查看 AimCodes ${total} 个无畏契约准星页面的真实统计，包括颜色、形状与合集数量，并直接预览和复制代码。`,
  }),
  ja: Object.freeze({
    navLabel: 'クロスヘア統計', eyebrow: 'AIMCODES データ', title: `${total}個のVALORANTクロスヘアコードを集計`, intro: `AimCodesで現在公開されている${total}個のクロスヘアページから、色・形・コレクションの傾向を確認できます。すべて開いてプレビューし、コピーできるコードです。`,
    summaryTitle: 'データの要点', summary: '白、シアン、赤が公開カタログの大部分を占めます。クラシックなライン型が最も多く、ドットや小型クロスヘアも十分な選択肢があります。AimCodes内の分布であり、全プレイヤーの使用率ではありません。',
    metrics: Object.freeze({ published: '公開コード', pros: 'プロ選手コード', colors: '色グループ', largest: '最大コレクション' }), colorTitle: 'カタログの色分布', colorIntro: '各ページの主な表示色を1回だけ集計します。対応が明確なカスタム色は最も近い基本色にまとめます。', categoryTitle: '形のグループ', categoryIntro: '各コードには主な形を1つだけ設定しているため、合計は重複しません。', collectionTitle: '今すぐ見られるコレクション', collectionIntro: 'コレクションは重複します。1つのクロスヘアが面白い・小さい・輪郭付きなど複数に入ることがあります。', table: Object.freeze({ group: 'グループ', codes: 'コード数', share: '公開ページの割合', open: 'コレクションを見る' }), colors: Object.freeze({ white: '白', cyan: 'シアン', red: '赤', pink: 'ピンク', green: '緑', yellow: '黄', black: '黒', custom: 'カスタム' }), categories: Object.freeze({ classic: 'クラシックなライン型', fun: '面白い・実験的', small: '小型クロスヘア', dot: 'ドットクロスヘア', cute: 'かわいい形' }), methodologyTitle: '集計方法', methodology: 'AimCodesは正規URLを持つインデックス可能な詳細ページだけを数えます。公開時に現在のカタログから再計算します。コレクションは重複するため合算できません。また、世界全体の使用率や勝率を示すものではありません。',
    sections: Object.freeze([Object.freeze({ title: 'データに含まれるもの', paragraphs: Object.freeze([`${total}個の公開ページには、使えるコード、プレビュー、コピーボタン、正規URLがあります。`, '下書き、重複、noindexページは除外されます。']), bullets: Object.freeze(['正規ページごとに1件。', '主な色と形はカタログ記録から集計。', 'コレクション数は現在の掲載内容から計算。']) }), Object.freeze({ title: 'この数字だけでは分からないこと', paragraphs: Object.freeze(['数が多いグループが最人気、または最強とは限りません。AimCodesの現在の構成を示す数字です。', '候補を絞る材料として使い、自分のマップとモニターで視認性を確認してください。']), bullets: Object.freeze(['カタログ比率は使用率ではありません。', 'プロのコードが必ず自分に最適とは限りません。', 'クロスヘアはプリエイムやストッピング練習の代わりにはなりません。']) }), Object.freeze({ title: 'データから候補を絞る', paragraphs: Object.freeze(['視認性、精度、面白さのどれを優先するか決め、対応する色や形のグループを開きます。', '同じマップ画面で比較し、1回に1項目だけ変えてください。']), bullets: Object.freeze(['目的を1つ選ぶ。', '同じシーンで比較する。', '候補を2つに絞って射撃場で試す。']) })]),
    faq: Object.freeze([Object.freeze(['AimCodesには何個のクロスヘアがありますか？', `この集計では正規URLを持つ${total}個のインデックス可能なページを数え、公開時に再計算します。`]), Object.freeze(['最も多い色は何ですか？', '現在は白が最多で、シアンと赤が僅差で続きます。AimCodes内の分布であり、全プレイヤーの傾向ではありません。']), Object.freeze(['1つのクロスヘアが複数のコレクションに入りますか？', 'はい。小型、ワンタップ、輪郭なしなど複数に入れます。色と形の各表では内部重複はありません。'])]), recommendedCrosshairIds: Object.freeze(['tenz', 'demon1', 'forsaken', 'cat-pink']), relatedArticleKeys: Object.freeze(['colors', 'dotVsCross', 'settings']), relatedCollectionKeys: Object.freeze(['funny', 'small', 'dot', 'pro']), relatedToolKeys: Object.freeze(['comparison', 'generator']), cta: 'データからクロスヘアを選ぶ', metaTitle: `${total}個のVALORANTクロスヘア統計：色と形 | AimCodes`, metaDescription: `AimCodesの${total}個のクロスヘアページから、色・形・コレクション数を集計。プレビューして使えるコードをコピーできます。`,
  }),
})

export function crosshairStatisticsCopy(locale) {
  return content[locale] || content.en
}
