const shared = {
  en: { selectionTitle: 'How these crosshairs were selected', settingsTitle: 'What to check before you copy', grid: 'Crosshairs to preview' },
  es: { selectionTitle: 'Cómo elegimos estas miras', settingsTitle: 'Qué revisar antes de copiar', grid: 'Miras para probar' },
  'pt-BR': { selectionTitle: 'Como escolhemos estas miras', settingsTitle: 'O que conferir antes de copiar', grid: 'Miras para testar' },
  'zh-CN': { selectionTitle: '这些准星怎么筛出来的', settingsTitle: '复制前先看这三点', grid: '直接预览这些准星' },
}

const related = {
  funny: { relatedCollectionKeys: ['cute', 'circle', 'pink', 'dot', 'small'], relatedArticleKeys: ['colors'], relatedToolKeys: ['preview', 'generator'] },
  white: { relatedCollectionKeys: ['minimalist', 'thin', 'withoutOutlines', 'dot', 'small'], relatedArticleKeys: ['colors', 'outlinesOnOff'], relatedToolKeys: ['comparison', 'preview'] },
  red: { relatedCollectionKeys: ['pink', 'thick', 'withOutlines'], relatedArticleKeys: ['colors', 'customColor'], relatedToolKeys: ['comparison', 'preview'] },
  thin: { relatedCollectionKeys: ['small', 'minimalist', 'openCenter'], relatedArticleKeys: ['thickness', 'gapOffset'], relatedToolKeys: ['generator', 'comparison'] },
  thick: { relatedCollectionKeys: ['beginner', 'closed', 'funny'], relatedArticleKeys: ['thickness', 'outlinesOnOff'], relatedToolKeys: ['preview', 'comparison'] },
  centerDot: { relatedCollectionKeys: ['dot', 'oneTap', 'closed'], relatedArticleKeys: ['centerDotOnOff', 'makeDot'], relatedToolKeys: ['generator', 'preview'] },
  withOutlines: { relatedCollectionKeys: ['white', 'small', 'centerDot'], relatedArticleKeys: ['outlinesOnOff', 'colors'], relatedToolKeys: ['comparison', 'generator'] },
  withoutOutlines: { relatedCollectionKeys: ['minimalist', 'thin', 'openCenter'], relatedArticleKeys: ['outlinesOnOff', 'colors'], relatedToolKeys: ['comparison', 'preview'] },
  openCenter: { relatedCollectionKeys: ['headshot', 'thin', 'vandal'], relatedArticleKeys: ['gapOffset', 'placement'], relatedToolKeys: ['generator', 'comparison'] },
  closed: { relatedCollectionKeys: ['centerDot', 'thick', 'phantom'], relatedArticleKeys: ['gapOffset', 'centerDotOnOff'], relatedToolKeys: ['preview', 'comparison'] },
}

const content = {
  en: {
    funny: {
      label: 'Funny crosshairs', eyebrow: 'BREAK THE DEFAULT CROSSHAIR', title: 'Funny VALORANT crosshair codes that actually work', intro: 'Preview animals, pixel goggles, portals, arcade buttons, totems, and oversized frames before taking a joke crosshair into your next match.',
      body: ['Funny crosshairs turn valid profile settings into recognizable shapes. They are useful for clips and casual games, but the larger geometry can hide distant targets.', 'Start with a compact heart, Pixel Sun, or Portal Ring, then compare it with Pixel Goggles, Neon Totem, Crosshairception, and Final Boss at normal scale. The funniest shape is not worth copying if you cannot still read the center.'],
      selection: 'Every item is a working AimCodes profile code with a visibly different silhouette. Near-duplicate color swaps were removed, and the expanded set is split across bold centers, wide HUD-style shapes, tall markers, and layered frames.',
      settings: ['Check how much of a distant head the shape covers.', 'Use a bright color that does not merge with your enemy outline.', 'Keep a compact ranked code in another profile slot.'],
      faq: [['Do funny VALORANT crosshairs work in game?', 'Yes. Every code on this page parses as a normal VALORANT profile, although large designs trade target clarity for personality.'], ['Which funny crosshair is easiest to aim with?', 'Pixel Sun, Portal Ring, Heart, and Flower keep a clearer center than the biggest frames and tall meme shapes.']],
      metaTitle: 'Funny VALORANT Crosshair Codes That Work | AimCodes', metaDescription: 'Preview funny VALORANT crosshair codes: animals, pixel goggles, portals, arcade targets, totems and frames. Test every working code before copying.',
    },
    white: {
      label: 'White crosshairs', eyebrow: 'CLEAN SHAPE, CAREFUL CONTRAST', title: 'White crosshair codes for VALORANT', intro: 'Copy and preview white VALORANT crosshair codes, from compact dots to clean crosses with or without outlines.',
      body: ['White makes compact geometry look neutral and uncluttered. It performs well on dark walls, but sky, pale stone, and ability flashes can erase a thin white center.', 'This collection mixes outlined and unoutlined shapes so you can test contrast without changing the base color. Compare them on one bright scene and one shadowed scene.'],
      selection: 'Only indexable codes whose active primary color resolves to white are included. The set covers dots, open crosses, compact crosses, and layered layouts.',
      settings: ['Try the code without an outline first.', 'Add a thin outline only when bright scenery hides the center.', 'Do not thicken every line to fix one bad background.'],
      faq: [['Is white a good VALORANT crosshair color?', 'Yes on darker and saturated surfaces; a thin outline may be needed on bright walls.'], ['Should a white crosshair always have outlines?', 'No. Use outlines only when they improve contrast without making the shape too bulky.']],
      metaTitle: 'White Crosshair Codes for VALORANT | AimCodes', metaDescription: 'Copy white crosshair codes for VALORANT, compare dots and crosses with or without outlines, and preview each setup on real map scenes.',
    },
    red: {
      label: 'Red crosshairs', eyebrow: 'HIGH CONTRAST ON COOL MAPS', title: 'Red VALORANT crosshair codes', intro: 'Test red dots and crosses on cool and neutral map scenes before pairing them with your enemy outline color.',
      body: ['Red can stand out sharply on blue-gray and green surfaces. It becomes harder to track on warm walls, damage effects, or red enemy outlines.', 'Keep the shape fixed while comparing red against cyan or white. If the red version disappears only when it reaches an enemy, the outline-color pairing is the problem.'],
      selection: 'Every item uses a working code with red as its active primary color. The list includes thin, thick, open, and closed shapes rather than repeated color variants.',
      settings: ['Avoid red when your enemy outline is also red.', 'Check orange and brick walls before ranked.', 'Use full opacity before adding thickness.'],
      faq: [['Is red a good crosshair color in VALORANT?', 'It can be excellent on cool maps, but it often conflicts with red enemy outlines and warm scenery.'], ['What enemy outline works with a red crosshair?', 'Yellow or purple usually separates more clearly than red, but test the pairing on your own display.']],
      metaTitle: 'Red VALORANT Crosshair Codes to Copy | AimCodes', metaDescription: 'Compare working red VALORANT crosshair codes on real map scenes. Test contrast, outlines and center shapes before copying a code.',
    },
    thin: {
      label: 'Thin crosshairs', eyebrow: 'LESS COVERAGE, MORE DISCIPLINE', title: 'Thin VALORANT crosshair codes', intro: 'Preview one-thickness lines that keep heads visible without shrinking the whole crosshair into a dot.',
      body: ['A thin crosshair reduces target coverage while preserving four-line direction. It is useful for long-range taps, but very short thin lines can disappear in utility.', 'The grid moves from tight micro gaps to wider open centers and layered marks. Judge line thickness separately from overall size.'],
      selection: 'The active inner lines in every selected code use thickness 1. We kept different lengths and offsets so the page compares genuinely different thin layouts.',
      settings: ['Use full opacity before increasing thickness.', 'Try a longer line if a short thin cross disappears.', 'Check whether an outline doubles the apparent weight.'],
      faq: [['What thickness is a thin VALORANT crosshair?', 'Thickness 1 is the usual thin-line baseline. Length and outline still change how heavy it looks.'], ['Are thin crosshairs better for headshots?', 'They cover less of the target, but only help if you can still locate the center quickly.']],
      metaTitle: 'Thin VALORANT Crosshair Codes & Settings | AimCodes', metaDescription: 'Preview thin VALORANT crosshair codes with one-thickness lines. Compare gaps, lengths and outlines, then copy a working profile.',
    },
    thick: {
      label: 'Thick crosshairs', eyebrow: 'KEEP THE CENTER VISIBLE', title: 'Thick VALORANT crosshair codes', intro: 'Compare high-visibility crosses and bold shapes for players who lose tiny sights during fast fights.',
      body: ['Thicker lines are easier to reacquire after a flick, ability effect, or rapid turn. The tradeoff is target coverage, especially against small heads at range.', 'Use these codes to find the minimum weight that remains visible. A compact thick cross often works better than making every line both thick and long.'],
      selection: 'Selected codes use inner-line thickness 3 or higher and remain visually distinct at normal preview scale. The set includes compact, tracking, and novelty layouts.',
      settings: ['Test at long range before copying.', 'Shorten the lines before reducing the thickness.', 'Avoid stacking a heavy outline on already-thick lines.'],
      faq: [['What is a thick crosshair good for?', 'It helps players who lose small sights during close fights or visual clutter.'], ['Does a thick crosshair reduce accuracy?', 'No, but it may cover more of the target and make fine corrections harder to read.']],
      metaTitle: 'Thick VALORANT Crosshair Codes for Visibility | AimCodes', metaDescription: 'Preview thick VALORANT crosshair codes that stay visible in busy fights. Compare compact and bold shapes before copying a working code.',
    },
    centerDot: {
      label: 'Center-dot crosshairs', eyebrow: 'MARK THE EXACT MIDDLE', title: 'VALORANT center-dot crosshair codes', intro: 'Try pure dots and dot-supported crosses that give your first bullet one clear center reference.',
      body: ['A center dot marks the exact middle even when inner or outer lines are also enabled. Pure dots keep the screen clean; supported dots give your eyes more shape to recover.', 'Compare dot size, outline, and supporting lines separately. A larger dot is not automatically worse if it keeps you from losing the center.'],
      selection: 'Every selected profile has the center-dot setting enabled. The grid mixes pure dots, short inner-line support, and outer markers.',
      settings: ['Start with full dot opacity.', 'Turn supporting lines off only after the dot stays visible.', 'Check how much the dot covers at long range.'],
      faq: [['What does center dot do in VALORANT?', 'It places a mark at the exact center of the crosshair and can be used alone or with lines.'], ['Can I use a center dot with inner lines?', 'Yes. Short lines can make a small dot easier to find without changing its exact center.']],
      metaTitle: 'VALORANT Center-Dot Crosshair Codes | AimCodes', metaDescription: 'Preview VALORANT center-dot crosshair codes, from pure dots to supported crosses. Test sizes and outlines, then copy a working code.',
    },
    withOutlines: {
      label: 'Crosshairs with outlines', eyebrow: 'EXTRA EDGE AGAINST BRIGHT WALLS', title: 'VALORANT crosshair codes with outlines', intro: 'Compare outlined dots and crosses when the center keeps disappearing into bright or low-contrast scenery.',
      body: ['Outlines place a dark edge around active crosshair elements. They can rescue white, cyan, and micro shapes on bright walls, but also make every line look heavier.', 'This grid includes several base shapes so you can judge the outline rather than assuming one pro code represents the whole setting.'],
      selection: 'Every code has outlines enabled and renders a visible edge at normal scale. We included dots, thin lines, compact crosses, and open centers.',
      settings: ['Begin with outline thickness 1.', 'Reduce line thickness if the combined shape looks bulky.', 'Compare the same scene with an unoutlined code.'],
      faq: [['Should outlines be on in VALORANT?', 'Turn them on when your crosshair disappears against bright surfaces; otherwise they are optional.'], ['Do outlines change weapon accuracy?', 'No. They only change the visual edge around the crosshair.']],
      metaTitle: 'VALORANT Crosshair Codes With Outlines | AimCodes', metaDescription: 'Preview VALORANT crosshair codes with outlines. Compare outlined dots and crosses on real maps, then copy the code that stays visible.',
    },
    withoutOutlines: {
      label: 'Crosshairs without outlines', eyebrow: 'CLEANER EDGES, LESS VISUAL WEIGHT', title: 'VALORANT crosshair codes without outlines', intro: 'Try clean dots and crosses without a dark border, then test whether their color alone stays visible.',
      body: ['Removing outlines keeps each line at its true thickness and can make a compact crosshair feel sharper. The cost is weaker contrast on bright or similarly colored walls.', 'Use a strong color before adding more geometry. Cyan, green, or red may remain readable without the extra border.'],
      selection: 'Every code has outlines disabled. The grid includes open, closed, thin, and dot-based layouts so you can compare clean edges across shapes.',
      settings: ['Use full opacity and a contrasting color.', 'Test both a bright wall and a dark corner.', 'Add an outline only if color changes do not fix visibility.'],
      faq: [['Are no-outline crosshairs better?', 'They look cleaner and thinner, but they are only better when the center remains visible.'], ['Which color works best without outlines?', 'Cyan and green are reliable first tests; red can work well on cooler map surfaces.']],
      metaTitle: 'VALORANT Crosshair Codes Without Outlines | AimCodes', metaDescription: 'Preview clean VALORANT crosshair codes without outlines. Compare dots, open centers and compact crosses before copying a code.',
    },
    openCenter: {
      label: 'Open-center crosshairs', eyebrow: 'LEAVE THE HEAD VISIBLE', title: 'Open-center VALORANT crosshair codes', intro: 'Compare crosshairs with a clear gap around the exact center for head-level placement and long-range fights.',
      body: ['An open center lets you see the target through the middle of four lines. It works well when you already trust your placement and want less target coverage.', 'If the gap becomes too wide, micro-corrections lose their reference. Compare several offsets on the same scene instead of copying a number blindly.'],
      selection: 'Selected codes use active inner lines with an offset of 3 or more. Different lengths and thicknesses keep the grid useful beyond one gap value.',
      settings: ['Start with offset 3–4.', 'Keep lines short enough to avoid a floating frame.', 'Pair a wider gap with clear line color.'],
      faq: [['What is an open-center crosshair?', 'It uses line offset to leave visible space around the exact center.'], ['Is a bigger crosshair gap better for headshots?', 'A moderate gap can keep the head visible, but a very wide gap makes precise centering harder.']],
      metaTitle: 'Open-Center VALORANT Crosshair Codes | AimCodes', metaDescription: 'Preview open-center VALORANT crosshair codes with clear gaps for head-level aim. Compare offsets and copy a working profile.',
    },
    closed: {
      label: 'Closed crosshairs', eyebrow: 'A STRONG, EASY-TO-FIND CENTER', title: 'Closed VALORANT crosshair codes', intro: 'Try compact crosses whose lines meet or nearly meet in the middle for fast center reacquisition.',
      body: ['A closed crosshair concentrates visual weight at the exact center. It is easy to find in close fights, but it can cover more of a distant head than an open gap.', 'The best closed shape stays compact. Compare line thickness and center dots before adding longer arms.'],
      selection: 'Selected codes use active inner lines with offset 0 or 1. We included both dot-supported and line-only centers at several weights.',
      settings: ['Keep the arms short at offset 0–1.', 'Test without a center dot before stacking both.', 'Check distant targets for excess coverage.'],
      faq: [['What is a closed VALORANT crosshair?', 'Its inner lines meet or sit very close to the middle, creating a solid visual center.'], ['Is closed better than open?', 'Closed is easier to find; open leaves more of the target visible. Your screen and aim style decide the tradeoff.']],
      metaTitle: 'Closed VALORANT Crosshair Codes & Preview | AimCodes', metaDescription: 'Preview compact closed VALORANT crosshair codes with strong centers. Compare line weight and dots, then copy a working code.',
    },
  },
  es: {},
  'pt-BR': {},
  'zh-CN': {},
}

const localizedSummaries = {
  es: {
    funny: ['Miras divertidas', 'MIRAS PARA CLIPS QUE SÍ FUNCIONAN', 'Códigos de miras divertidas de VALORANT', 'Prueba animales, gafas píxel, portales, botones arcade, tótems y marcos antes de llevar una mira de broma a partida.', 'Estas formas usan códigos reales, pero las más grandes pueden tapar rivales lejanos.', 'Empieza con Sol Píxel o Anillo Portal y compáralos con Gafas Píxel, Tótem Neón, Mira Dentro de Mira y Jefe Final.', 'Incluimos siluetas de cuatro familias distintas y quitamos cambios de color repetidos.', ['Mira cuánto tapa una cabeza lejana.', 'Usa un color que no se mezcle con el contorno enemigo.', 'Guarda otra mira compacta para ranked.'], ['¿Funcionan estas miras en VALORANT?', 'Sí, todos los códigos de esta página son perfiles válidos; las formas grandes sacrifican claridad.', '¿Cuál es la más fácil para apuntar?', 'Sol Píxel, Anillo Portal, Corazón y Flor dejan el centro más limpio que los marcos grandes.'], 'Miras Divertidas de VALORANT que Funcionan | AimCodes', 'Prueba miras divertidas de VALORANT: animales, gafas píxel, portales, tótems y marcos. Compara cada código válido antes de copiar.'],
    white: ['Miras blancas', 'FORMA LIMPIA, CONTRASTE CON CUIDADO', 'Códigos de miras blancas de VALORANT', 'Compara puntos y cruces blancas y decide si necesitan contorno en zonas claras.', 'El blanco se ve limpio en paredes oscuras, pero puede desaparecer en cielo y piedra clara.', 'La colección mezcla formas con y sin contorno para probar contraste sin cambiar el color.', 'Solo incluimos códigos indexables cuyo color principal activo es blanco.', ['Prueba primero sin contorno.', 'Añade un borde fino solo si se pierde.', 'No engordes toda la mira por una sola pared.'], ['¿El blanco es buen color?', 'Sí en superficies oscuras; en paredes claras puede necesitar contorno.', '¿Siempre necesita borde?', 'No, solo cuando mejora el contraste sin volver pesada la forma.'], 'Códigos de Miras Blancas de VALORANT | AimCodes', 'Prueba miras blancas de VALORANT con y sin contorno. Compara puntos y cruces en mapas reales y copia el código.'],
    red: ['Miras rojas', 'CONTRASTE EN MAPAS FRÍOS', 'Códigos de miras rojas de VALORANT', 'Prueba puntos y cruces rojas antes de combinarlos con el color del contorno enemigo.', 'El rojo destaca en superficies frías, pero se pierde en paredes cálidas y contornos rojos.', 'Compara la misma forma en rojo, cian y blanco para separar color de geometría.', 'Todos los códigos usan rojo como color principal y ofrecen formas distintas.', ['Evita rojo con contorno enemigo rojo.', 'Revisa paredes naranjas y de ladrillo.', 'Usa opacidad completa antes de engordar.'], ['¿El rojo es buen color?', 'Puede ser excelente en mapas fríos, pero choca con contornos rojos.', '¿Qué contorno combina mejor?', 'Amarillo o morado suelen separarse mejor.'], 'Códigos de Miras Rojas de VALORANT | AimCodes', 'Compara códigos de miras rojas de VALORANT en mapas reales. Prueba contraste, borde y forma antes de copiar.'],
    thin: ['Miras finas', 'MENOS COBERTURA, MÁS DISCIPLINA', 'Códigos de miras finas de VALORANT', 'Prueba líneas de grosor 1 que dejan la cabeza visible sin convertir todo en un punto.', 'Una mira fina cubre menos objetivo, pero puede desaparecer entre habilidades.', 'La cuadrícula compara microespacios, centros abiertos y marcas dobles.', 'Todas las miras seleccionadas usan grosor interior 1 y varias longitudes.', ['Usa opacidad completa.', 'Alarga la línea antes de engordarla.', 'Comprueba si el contorno duplica el peso.'], ['¿Qué grosor se considera fino?', 'El valor 1 es la base habitual.', '¿Es mejor para headshots?', 'Cubre menos, pero solo ayuda si encuentras el centro rápido.'], 'Códigos de Miras Finas de VALORANT | AimCodes', 'Prueba miras finas de VALORANT con líneas de grosor 1. Compara huecos, longitudes y contornos y copia un código válido.'],
    thick: ['Miras gruesas', 'NO PIERDAS EL CENTRO', 'Códigos de miras gruesas de VALORANT', 'Compara cruces visibles y formas marcadas para peleas rápidas y pantallas cargadas.', 'Las líneas gruesas se recuperan rápido, pero tapan más los objetivos lejanos.', 'Busca el peso mínimo que sigues viendo; corto y grueso suele ser mejor que largo y grueso.', 'Incluimos códigos con grosor interior 3 o superior y siluetas distintas.', ['Prueba primero a larga distancia.', 'Acorta líneas antes de bajar grosor.', 'No apiles un contorno pesado.'], ['¿Para qué sirve una mira gruesa?', 'Para no perder el centro en peleas cercanas o con muchos efectos.', '¿Reduce la precisión?', 'No, pero tapa más y dificulta leer microajustes.'], 'Códigos de Miras Gruesas de VALORANT | AimCodes', 'Prueba miras gruesas de VALORANT que siguen visibles en peleas cargadas. Compara formas compactas y copia un código válido.'],
    centerDot: ['Miras con punto central', 'MARCA EL CENTRO EXACTO', 'Códigos de mira con punto central de VALORANT', 'Prueba puntos puros y cruces con punto para dar una referencia clara a la primera bala.', 'El punto marca el medio exacto; las líneas de apoyo ayudan a recuperarlo.', 'Compara tamaño, contorno y líneas por separado antes de decidir.', 'Todos los perfiles seleccionados tienen activado el punto central.', ['Empieza con opacidad completa.', 'Quita las líneas solo si sigues viendo el punto.', 'Mira cuánto tapa a larga distancia.'], ['¿Qué hace el punto central?', 'Coloca una marca exacta en el centro y puede usarse solo o con líneas.', '¿Puede usarse con líneas internas?', 'Sí, unas líneas cortas ayudan a encontrarlo.'], 'Códigos de Mira con Punto Central de VALORANT | AimCodes', 'Prueba códigos de mira con punto central de VALORANT, desde puntos puros hasta cruces con apoyo. Compara y copia.'],
    withOutlines: ['Miras con contorno', 'UN BORDE EXTRA EN PAREDES CLARAS', 'Códigos de miras de VALORANT con contorno', 'Compara puntos y cruces con borde cuando el centro desaparece en fondos claros.', 'El contorno añade un borde oscuro, mejora contraste y también engorda la forma.', 'La colección usa varias geometrías para evaluar el ajuste, no una sola mira pro.', 'Todos los códigos tienen contorno activo y visible a escala normal.', ['Empieza con grosor de contorno 1.', 'Reduce las líneas si queda demasiado pesado.', 'Compara con una versión sin contorno.'], ['¿Debería activar el contorno?', 'Sí cuando la mira se pierde en zonas claras; si no, es opcional.', '¿Cambia la precisión?', 'No, solo cambia el borde visual.'], 'Códigos de Miras de VALORANT con Contorno | AimCodes', 'Prueba códigos de miras de VALORANT con contorno. Compara puntos y cruces en mapas reales y copia el más visible.'],
    withoutOutlines: ['Miras sin contorno', 'BORDES LIMPIOS, MENOS PESO', 'Códigos de miras de VALORANT sin contorno', 'Prueba puntos y cruces limpios sin borde oscuro y comprueba si el color basta.', 'Sin contorno, las líneas conservan su grosor real, pero pierden contraste en paredes claras.', 'Usa primero un color fuerte antes de añadir más geometría.', 'Todos los códigos tienen el contorno desactivado e incluyen formas distintas.', ['Usa opacidad completa y color contrastado.', 'Prueba una pared clara y una esquina oscura.', 'Añade borde solo si el color no lo resuelve.'], ['¿Son mejores sin contorno?', 'Se ven más limpias, pero solo si el centro sigue visible.', '¿Qué color funciona mejor?', 'Cian y verde son puntos de partida seguros.'], 'Códigos de Miras de VALORANT sin Contorno | AimCodes', 'Prueba códigos limpios de miras de VALORANT sin contorno. Compara puntos y cruces y copia un código válido.'],
    openCenter: ['Miras con centro abierto', 'DEJA LA CABEZA VISIBLE', 'Códigos de miras de VALORANT con centro abierto', 'Compara cruces con espacio central para preaim y duelos a larga distancia.', 'El hueco deja ver el objetivo; si es demasiado grande, faltará referencia para corregir.', 'Compara varios offsets en la misma escena en lugar de copiar un número.', 'Seleccionamos líneas internas activas con offset 3 o superior.', ['Empieza con offset 3–4.', 'Mantén las líneas cortas.', 'Combina hueco amplio con color claro.'], ['¿Qué es un centro abierto?', 'Líneas separadas que dejan espacio visible alrededor del centro.', '¿Más hueco mejora los headshots?', 'Un hueco moderado ayuda; uno enorme dificulta centrar.'], 'Códigos de Mira con Centro Abierto de VALORANT | AimCodes', 'Prueba miras de VALORANT con centro abierto para apuntar a la cabeza. Compara offsets y copia un código válido.'],
    closed: ['Miras cerradas', 'UN CENTRO FUERTE Y FÁCIL DE ENCONTRAR', 'Códigos de miras cerradas de VALORANT', 'Prueba cruces compactas cuyas líneas se juntan o casi se juntan en el centro.', 'El centro cerrado se encuentra rápido, pero tapa más una cabeza lejana.', 'La mejor forma cerrada sigue siendo compacta; prueba grosor antes de alargar.', 'Seleccionamos líneas internas con offset 0 o 1 y varios pesos.', ['Mantén brazos cortos.', 'Prueba sin punto antes de apilar ambos.', 'Revisa objetivos lejanos.'], ['¿Qué es una mira cerrada?', 'Sus líneas se juntan o quedan muy cerca del centro.', '¿Es mejor que una abierta?', 'Es más fácil de encontrar; la abierta tapa menos.'], 'Códigos de Miras Cerradas de VALORANT | AimCodes', 'Prueba códigos compactos de miras cerradas de VALORANT. Compara grosor y punto central y copia un código válido.'],
  },
  'pt-BR': {
    funny: ['Miras divertidas', 'FORMAS PARA CLIPES QUE FUNCIONAM', 'Códigos de miras divertidas do VALORANT', 'Teste animais, óculos pixel, portais, botões arcade, totens e molduras antes de levar uma mira de brincadeira para a partida.', 'As formas usam códigos reais, mas as maiores podem cobrir alvos distantes.', 'Comece com Sol Pixel ou Anel Portal e compare com Óculos Pixel, Totem Neon, Mira Dentro da Mira e Chefão Final.', 'Incluímos quatro famílias de silhuetas e removemos simples trocas de cor.', ['Veja quanto cobre uma cabeça distante.', 'Use uma cor diferente do contorno inimigo.', 'Guarde uma mira compacta em outro perfil.'], ['Essas miras funcionam?', 'Sim, todos os códigos desta página são perfis válidos; formatos grandes sacrificam clareza.', 'Qual é mais fácil de usar?', 'Sol Pixel, Anel Portal, Coração e Flor deixam o centro mais limpo que as molduras grandes.'], 'Miras Divertidas do VALORANT que Funcionam | AimCodes', 'Teste miras divertidas do VALORANT: animais, óculos pixel, portais, totens e molduras. Compare cada código antes de copiar.'],
    white: ['Miras brancas', 'FORMA LIMPA, CONTRASTE COM CUIDADO', 'Códigos de miras brancas do VALORANT', 'Compare pontos e cruzes brancas e decida se precisam de contorno em áreas claras.', 'O branco fica limpo em paredes escuras, mas some no céu e pedra clara.', 'A coleção mistura formas com e sem contorno para testar contraste.', 'Só incluímos códigos indexáveis com branco como cor principal.', ['Teste primeiro sem contorno.', 'Adicione borda fina só se sumir.', 'Não engrosse tudo por causa de uma parede.'], ['Branco é uma boa cor?', 'Sim em áreas escuras; em paredes claras pode precisar de contorno.', 'Sempre precisa de borda?', 'Não, apenas quando melhora o contraste.'], 'Códigos de Miras Brancas do VALORANT | AimCodes', 'Teste miras brancas do VALORANT com e sem contorno. Compare pontos e cruzes em mapas reais e copie o código.'],
    red: ['Miras vermelhas', 'CONTRASTE EM MAPAS FRIOS', 'Códigos de miras vermelhas do VALORANT', 'Teste pontos e cruzes vermelhas antes de combinar com o contorno inimigo.', 'Vermelho aparece em superfícies frias, mas some em paredes quentes e contorno vermelho.', 'Compare a mesma forma em vermelho, ciano e branco.', 'Todos os códigos usam vermelho como cor principal e têm formas distintas.', ['Evite vermelho com contorno vermelho.', 'Confira paredes laranja e de tijolo.', 'Use opacidade total antes de engrossar.'], ['Vermelho é uma boa cor?', 'Pode ser ótimo em mapas frios, mas conflita com contorno vermelho.', 'Qual contorno combina?', 'Amarelo ou roxo costumam separar melhor.'], 'Códigos de Miras Vermelhas do VALORANT | AimCodes', 'Compare códigos de miras vermelhas do VALORANT em mapas reais. Teste contraste e formato antes de copiar.'],
    thin: ['Miras finas', 'MENOS COBERTURA, MAIS DISCIPLINA', 'Códigos de miras finas do VALORANT', 'Teste linhas de espessura 1 que deixam a cabeça visível sem virar apenas um ponto.', 'Uma mira fina cobre menos, mas pode sumir entre habilidades.', 'A grade compara microespaços, centros abertos e marcas duplas.', 'Todas usam espessura interna 1 e comprimentos diferentes.', ['Use opacidade total.', 'Alongue antes de engrossar.', 'Veja se o contorno dobra o peso.'], ['Qual espessura é fina?', 'O valor 1 é a base normal.', 'É melhor para headshots?', 'Cobre menos, mas só ajuda se você achar o centro rápido.'], 'Códigos de Miras Finas do VALORANT | AimCodes', 'Teste miras finas do VALORANT com linhas de espessura 1. Compare espaços e contornos e copie um código.'],
    thick: ['Miras grossas', 'NÃO PERCA O CENTRO', 'Códigos de miras grossas do VALORANT', 'Compare cruzes visíveis e formatos marcantes para lutas rápidas.', 'Linhas grossas voltam ao olhar rápido, mas cobrem mais alvos distantes.', 'Busque o menor peso que continua visível.', 'Incluímos espessura interna 3 ou maior e silhuetas diferentes.', ['Teste de longe primeiro.', 'Encurte linhas antes de afinar.', 'Não use contorno pesado.'], ['Para que serve mira grossa?', 'Para não perder o centro em lutas próximas ou cheias de efeitos.', 'Reduz precisão?', 'Não, mas cobre mais e dificulta microcorreções.'], 'Códigos de Miras Grossas do VALORANT | AimCodes', 'Teste miras grossas do VALORANT que ficam visíveis em lutas carregadas. Compare e copie um código válido.'],
    centerDot: ['Miras com ponto central', 'MARQUE O MEIO EXATO', 'Códigos de mira com ponto central do VALORANT', 'Teste pontos puros e cruzes com ponto para ter uma referência clara na primeira bala.', 'O ponto marca o meio; linhas de apoio ajudam a reencontrá-lo.', 'Compare tamanho, contorno e linhas separadamente.', 'Todos os perfis selecionados têm ponto central ativo.', ['Comece com opacidade total.', 'Desligue linhas só se ainda enxergar o ponto.', 'Veja quanto cobre de longe.'], ['O que faz o ponto central?', 'Marca o centro exato e pode funcionar sozinho ou com linhas.', 'Pode usar com linhas internas?', 'Sim, linhas curtas ajudam a encontrá-lo.'], 'Códigos de Mira com Ponto Central do VALORANT | AimCodes', 'Teste códigos de mira com ponto central do VALORANT, de pontos puros a cruzes com apoio. Compare e copie.'],
    withOutlines: ['Miras com contorno', 'UMA BORDA EXTRA EM PAREDES CLARAS', 'Códigos de miras do VALORANT com contorno', 'Compare pontos e cruzes com borda quando o centro some em fundos claros.', 'O contorno melhora contraste e também deixa a forma mais pesada.', 'A coleção usa geometrias diferentes para avaliar a configuração.', 'Todos os códigos têm contorno ativo e visível.', ['Comece com espessura 1.', 'Reduza as linhas se ficar pesado.', 'Compare com uma versão sem contorno.'], ['Devo ligar o contorno?', 'Sim quando a mira some em áreas claras; caso contrário é opcional.', 'Muda a precisão?', 'Não, apenas o visual.'], 'Códigos de Miras do VALORANT com Contorno | AimCodes', 'Teste códigos de miras do VALORANT com contorno. Compare pontos e cruzes em mapas reais e copie o mais visível.'],
    withoutOutlines: ['Miras sem contorno', 'BORDAS LIMPAS, MENOS PESO', 'Códigos de miras do VALORANT sem contorno', 'Teste pontos e cruzes limpos sem borda escura e veja se a cor basta.', 'Sem contorno, as linhas mantêm a espessura real, mas perdem contraste.', 'Use primeiro uma cor forte antes de adicionar geometria.', 'Todos os códigos têm contorno desligado e formas variadas.', ['Use opacidade total.', 'Teste parede clara e canto escuro.', 'Adicione borda só se a cor não resolver.'], ['São melhores sem contorno?', 'Ficam mais limpas, mas só se o centro continuar visível.', 'Qual cor funciona?', 'Ciano e verde são bons começos.'], 'Códigos de Miras do VALORANT sem Contorno | AimCodes', 'Teste códigos limpos de miras do VALORANT sem contorno. Compare pontos e cruzes e copie um código.'],
    openCenter: ['Miras com centro aberto', 'DEIXE A CABEÇA VISÍVEL', 'Códigos de miras do VALORANT com centro aberto', 'Compare cruzes com espaço central para preaim e duelos longos.', 'O espaço mostra o alvo; se for grande demais, falta referência para corrigir.', 'Compare vários offsets na mesma cena.', 'Selecionamos linhas internas com offset 3 ou maior.', ['Comece com offset 3–4.', 'Mantenha linhas curtas.', 'Use cor clara com espaço amplo.'], ['O que é centro aberto?', 'Linhas separadas deixam espaço visível ao redor do meio.', 'Mais espaço melhora headshots?', 'Um espaço moderado ajuda; enorme dificulta centralizar.'], 'Códigos de Mira com Centro Aberto do VALORANT | AimCodes', 'Teste miras do VALORANT com centro aberto para mirar na cabeça. Compare offsets e copie um código.'],
    closed: ['Miras fechadas', 'UM CENTRO FORTE E FÁCIL DE ACHAR', 'Códigos de miras fechadas do VALORANT', 'Teste cruzes compactas cujas linhas se encontram no centro.', 'O centro fechado é fácil de achar, mas cobre mais a cabeça distante.', 'A melhor forma fechada continua compacta.', 'Selecionamos offset 0 ou 1 e vários pesos.', ['Mantenha braços curtos.', 'Teste sem ponto antes de combinar.', 'Confira alvos distantes.'], ['O que é mira fechada?', 'As linhas se encontram ou ficam muito perto do centro.', 'É melhor que aberta?', 'É mais fácil de achar; a aberta cobre menos.'], 'Códigos de Miras Fechadas do VALORANT | AimCodes', 'Teste códigos compactos de miras fechadas do VALORANT. Compare peso e ponto e copie um código.'],
  },
  'zh-CN': {
    funny: ['整活准星', '好玩，但得真的能用', '无畏契约整活准星代码', '动物脸、像素护目镜、传送门、街机按钮、图腾和大框架都能直接预览，别把只适合截图的准星直接带进排位。', '整活准星同样由有效配置代码组成，只是更大的图案会遮住远处目标。', '先试像素太阳或传送门圆环，再比较像素护目镜、霓虹图腾、准星套娃和最终首领在正常比例下有多占画面。', '按醒目中心、横向界面、纵向标记和双层框架四类扩充，只保留轮廓明显不同的有效造型。', ['先看远距离会不会挡头。', '颜色不要和敌人轮廓撞在一起。', '另存一个紧凑准星用于认真打排位。'], ['整活准星真的能在游戏里用吗？', '能，本页每个代码都能被正常解析；只是大图案会用目标清晰度换趣味性。', '哪种整活准星最容易瞄？', '像素太阳、传送门圆环、爱心和花朵的中心比大框架更清楚。'], '无畏契约整活准星代码：像素、图腾与更多 | AimCodes', '预览可用的无畏契约整活准星代码，包括动物、像素护目镜、传送门、图腾和框架，试过效果再复制。'],
    white: ['白色准星', '画面干净，对比度要自己补', '无畏契约白色准星代码', '把白色圆点和十字放到亮暗场景里一起看，再决定是否需要轮廓。', '白色在暗墙上非常干净，但天空、浅色石墙和闪光效果都可能把细小中心吃掉。', '这一组同时保留有轮廓和无轮廓造型，让你只比较对比度，不用先换颜色。', '仅收录主颜色确实为白色的可索引有效代码，并覆盖圆点、开放十字与双层造型。', ['先关闭轮廓试一次。', '只有亮墙会吃掉中心时才加细轮廓。', '不要因为一张地图就把所有线条加粗。'], ['白色适合当准星颜色吗？', '适合暗色和高饱和场景；亮墙上通常需要一层细轮廓。', '白色准星一定要开轮廓吗？', '不一定，只有轮廓能改善可见度且不会让造型变笨重时才需要。'], '无畏契约白色准星代码与预览 | AimCodes', '预览带轮廓和不带轮廓的无畏契约白色准星，在真实地图中比较圆点和十字并复制代码。'],
    red: ['红色准星', '冷色地图里更显眼', '无畏契约红色准星代码', '先在冷色与中性地图中测试红色圆点和十字，再决定敌人轮廓该怎么配。', '红色在蓝灰和绿色表面很突出，却容易融进暖墙、伤害特效和红色敌人轮廓。', '固定形状后再对比红、青、白三种颜色，才能判断问题来自颜色还是造型。', '每个代码的主颜色都是红色，并保留粗细、中心留空和轮廓不同的造型。', ['敌人轮廓是红色时不要再用红准星。', '重点检查橙墙和砖墙。', '先拉满透明度，再考虑加粗。'], ['红色准星好用吗？', '冷色地图里会很醒目，但和红色敌人轮廓容易打架。', '红准星配什么敌人轮廓？', '黄色或紫色通常更容易区分，最终仍要看自己的显示器。'], '无畏契约红色准星代码与地图预览 | AimCodes', '在真实地图中比较无畏契约红色准星代码，测试颜色对比、轮廓和中心形状后再复制。'],
    thin: ['细线准星', '少挡一点，枪线更清楚', '无畏契约细线准星代码', '直接比较粗细为 1 的短线、微距留空和开放十字，不必把整个准星缩成一个点。', '细线会少挡目标，适合中远距离单点；但线又短又细时，很容易被技能特效吃掉。', '这组同时包含窄留空、宽留空和双层标记，能把线条粗细和整体大小分开看。', '所有入选准星的内线粗细都是 1，并用不同长度和偏移避免近似重复。', ['先使用完整不透明度。', '看不清时先加长，不要立刻加粗。', '注意轮廓会不会让视觉粗细翻倍。'], ['无畏契约准星粗细多少算细？', '粗细 1 是常见的细线起点，长度和轮廓也会改变视觉重量。', '细线准星更容易爆头吗？', '它确实少挡目标，但只有你能快速找到中心时才有帮助。'], '无畏契约细线准星代码与参数 | AimCodes', '预览粗细为 1 的无畏契约细线准星，对比长度、间距和轮廓并复制有效代码。'],
    thick: ['粗线准星', '混战里别把中心看丢', '无畏契约粗线准星代码', '适合经常在快速转身、技能特效和近距离混战里看丢小准星的玩家。', '粗线更容易被视线重新捕捉，代价是远距离会遮住更多头部。', '目标不是越粗越好，而是找到你还能稳定看见的最小重量；短粗线通常比又长又粗更实用。', '只收录内线粗细不低于 3、且在正常比例下轮廓明显不同的代码。', ['先拿远距离目标测试。', '觉得太挡时先缩短线条。', '已经很粗就不要再叠厚轮廓。'], ['粗线准星适合什么玩家？', '适合在近距离或画面复杂时容易丢失小准星的玩家。', '粗准星会降低武器精度吗？', '不会，但它会多挡目标，让细微修枪更难观察。'], '无畏契约粗线准星代码：高可见度造型 | AimCodes', '预览混战中更醒目的无畏契约粗线准星，对比紧凑与大号造型并复制有效代码。'],
    centerDot: ['中心点准星', '把正中心钉死', '无畏契约中心点准星代码', '从纯圆点到带短线辅助的中心点都能直接试，给第一枪一个明确参照。', '中心点直接标记正中；纯点最干净，短线辅助则更容易在移动后找回来。', '把圆点大小、轮廓和辅助线分开比较，不要看到点大一点就直接否定。', '所有入选配置都开启了中心点，并覆盖纯点、短内线和外线辅助。', ['先把中心点不透明度拉满。', '能稳定看见圆点后再关辅助线。', '重点看远距离会遮住多少头部。'], ['中心点选项有什么用？', '它会在准星正中心放一个标记，可以单独使用，也可以配合内外线。', '中心点能和内线一起开吗？', '可以，短内线能帮助视线找回较小的圆点。'], '无畏契约中心点准星代码与预览 | AimCodes', '预览无畏契约中心点准星代码，从纯圆点到带短线辅助的造型，比较大小与轮廓后直接复制。'],
    withOutlines: ['带轮廓准星', '亮墙上多一层边', '无畏契约带轮廓准星代码', '如果准星总是在亮墙和低对比度场景里消失，先比较这些带轮廓圆点与十字。', '轮廓会给启用的准星元素加一层深色边，能提升对比度，也会让线条看起来更粗。', '这里保留多种基础造型，避免你拿一个职业准星就判断整个轮廓功能。', '每个代码都确实开启轮廓，并能在正常预览比例下看到边缘。', ['轮廓粗细先从 1 开始。', '整体变笨重时先降低线条粗细。', '在同一场景对比无轮廓版本。'], ['无畏契约准星轮廓应该开吗？', '准星会在亮场景消失时建议开，否则它只是可选项。', '轮廓会改变射击精度吗？', '不会，它只改变准星边缘的视觉效果。'], '无畏契约带轮廓准星代码 | AimCodes', '预览带轮廓的无畏契约准星代码，在真实地图中比较圆点和十字并复制最清楚的造型。'],
    withoutOutlines: ['无轮廓准星', '边缘更干净，视觉更轻', '无畏契约无轮廓准星代码', '直接试不带深色边缘的圆点和十字，看看只靠颜色能不能保持清楚。', '关闭轮廓后，线条会保持真实粗细，造型更利落；亮墙和相近颜色表面上的对比度则会下降。', '先换一个更醒目的颜色，不要一看不清就继续增加线条。', '所有代码都关闭了轮廓，并覆盖开放、闭合、细线和圆点造型。', ['使用完整不透明度和对比色。', '一张亮墙和一个暗角都要试。', '换色仍看不清时再考虑轮廓。'], ['无轮廓准星更好吗？', '它更干净、更轻，但前提是中心仍然清楚。', '不用轮廓时什么颜色更稳？', '青色和绿色是更稳妥的起点，冷色地图也可以试红色。'], '无畏契约无轮廓准星代码 | AimCodes', '预览干净的无畏契约无轮廓准星，对比圆点、开放中心和紧凑十字并复制有效代码。'],
    openCenter: ['中心留空准星', '让头部留在中心空隙里', '无畏契约中心留空准星代码', '比较中心有明显空隙的十字，适合头线预瞄和中远距离对枪。', '中心留空会让你直接看见四条线中间的目标；空隙太大时，细微修枪又会缺少参照。', '固定地图比较多个偏移值，不要只凭别人说的一个数字决定。', '所有入选配置都开启内线，且偏移不低于 3，并保留不同长度和粗细。', ['先从偏移 3–4 开始。', '线条不要长到像漂浮外框。', '空隙越大，线条颜色越要清楚。'], ['什么是中心留空准星？', '通过内线偏移，在正中心周围留下能看见目标的空隙。', '中心空隙越大越容易爆头吗？', '适中空隙能少挡头，太大反而不容易精确居中。'], '无畏契约中心留空准星代码 | AimCodes', '预览适合头线瞄准的无畏契约中心留空准星，对比偏移参数并复制有效代码。'],
    closed: ['中心闭合准星', '中心更实，更容易找回来', '无畏契约中心闭合准星代码', '比较四条线在中间相接或接近相接的紧凑十字，快速转火时更容易定位。', '闭合中心会把视觉重量集中在正中，近距离很好找，但会比留空准星多挡一点远处头部。', '好用的闭合造型仍然应该紧凑，先比较粗细和中心点，再决定要不要加长。', '入选代码的内线偏移为 0 或 1，并包含纯线和带中心点的不同重量。', ['偏移 0–1 时保持短线。', '先试纯线，再决定是否叠中心点。', '一定要拿远距离目标检查遮挡。'], ['什么是中心闭合准星？', '四条内线在中间相接或非常接近，形成更实的中心。', '闭合和留空哪个更好？', '闭合更好找，留空更少挡目标，要按屏幕和瞄准习惯选择。'], '无畏契约中心闭合准星代码与预览 | AimCodes', '预览紧凑的无畏契约中心闭合准星，对比线条粗细与中心点并复制有效代码。'],
  },
}

function makeLocalized(locale, key, values) {
  const [label, eyebrow, title, intro, bodyOne, bodyTwo, selection, settings, faq, metaTitle, metaDescription] = values
  return {
    label, eyebrow, title, intro, gridTitle: shared[locale].grid,
    body: [bodyOne, bodyTwo], selectionTitle: shared[locale].selectionTitle, selection,
    settingsTitle: shared[locale].settingsTitle, settings,
    faq: [[faq[0], faq[1]], [faq[2], faq[3]]], metaTitle, metaDescription,
    ...related[key],
  }
}

for (const locale of ['es', 'pt-BR', 'zh-CN']) {
  content[locale] = Object.fromEntries(Object.entries(localizedSummaries[locale]).map(([key, values]) => [key, makeLocalized(locale, key, values)]))
}

for (const [key, value] of Object.entries(content.en)) {
  content.en[key] = { ...value, gridTitle: shared.en.grid, selectionTitle: shared.en.selectionTitle, settingsTitle: shared.en.settingsTitle, ...related[key] }
}

export function growthCollectionCopy(locale, collectionKey) {
  return content[locale]?.[collectionKey] || content.en[collectionKey] || null
}
